// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: hookly/v1/relay.proto

package hooklyv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hooks.dx314.com/internal/api/hookly/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RelayServiceName is the fully-qualified name of the RelayService service.
	RelayServiceName = "hookly.v1.RelayService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RelayServiceStreamProcedure is the fully-qualified name of the RelayService's Stream RPC.
	RelayServiceStreamProcedure = "/hookly.v1.RelayService/Stream"
)

// RelayServiceClient is a client for the hookly.v1.RelayService service.
type RelayServiceClient interface {
	// Stream establishes a bidirectional stream.
	// Home-hub sends auth message, then receives webhooks.
	// Home-hub sends delivery acks to report delivery status.
	Stream(context.Context) *connect.BidiStreamForClient[v1.StreamRequest, v1.StreamResponse]
}

// NewRelayServiceClient constructs a client for the hookly.v1.RelayService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRelayServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RelayServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	relayServiceMethods := v1.File_hookly_v1_relay_proto.Services().ByName("RelayService").Methods()
	return &relayServiceClient{
		stream: connect.NewClient[v1.StreamRequest, v1.StreamResponse](
			httpClient,
			baseURL+RelayServiceStreamProcedure,
			connect.WithSchema(relayServiceMethods.ByName("Stream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// relayServiceClient implements RelayServiceClient.
type relayServiceClient struct {
	stream *connect.Client[v1.StreamRequest, v1.StreamResponse]
}

// Stream calls hookly.v1.RelayService.Stream.
func (c *relayServiceClient) Stream(ctx context.Context) *connect.BidiStreamForClient[v1.StreamRequest, v1.StreamResponse] {
	return c.stream.CallBidiStream(ctx)
}

// RelayServiceHandler is an implementation of the hookly.v1.RelayService service.
type RelayServiceHandler interface {
	// Stream establishes a bidirectional stream.
	// Home-hub sends auth message, then receives webhooks.
	// Home-hub sends delivery acks to report delivery status.
	Stream(context.Context, *connect.BidiStream[v1.StreamRequest, v1.StreamResponse]) error
}

// NewRelayServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRelayServiceHandler(svc RelayServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	relayServiceMethods := v1.File_hookly_v1_relay_proto.Services().ByName("RelayService").Methods()
	relayServiceStreamHandler := connect.NewBidiStreamHandler(
		RelayServiceStreamProcedure,
		svc.Stream,
		connect.WithSchema(relayServiceMethods.ByName("Stream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/hookly.v1.RelayService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RelayServiceStreamProcedure:
			relayServiceStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRelayServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRelayServiceHandler struct{}

func (UnimplementedRelayServiceHandler) Stream(context.Context, *connect.BidiStream[v1.StreamRequest, v1.StreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("hookly.v1.RelayService.Stream is not implemented"))
}
