// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hookly/v1/common.proto

package hooklyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Provider type for webhook signature verification
type ProviderType int32

const (
	ProviderType_PROVIDER_TYPE_UNSPECIFIED ProviderType = 0
	ProviderType_PROVIDER_TYPE_STRIPE      ProviderType = 1
	ProviderType_PROVIDER_TYPE_GITHUB      ProviderType = 2
	ProviderType_PROVIDER_TYPE_TELEGRAM    ProviderType = 3
	ProviderType_PROVIDER_TYPE_GENERIC     ProviderType = 4
)

// Enum value maps for ProviderType.
var (
	ProviderType_name = map[int32]string{
		0: "PROVIDER_TYPE_UNSPECIFIED",
		1: "PROVIDER_TYPE_STRIPE",
		2: "PROVIDER_TYPE_GITHUB",
		3: "PROVIDER_TYPE_TELEGRAM",
		4: "PROVIDER_TYPE_GENERIC",
	}
	ProviderType_value = map[string]int32{
		"PROVIDER_TYPE_UNSPECIFIED": 0,
		"PROVIDER_TYPE_STRIPE":      1,
		"PROVIDER_TYPE_GITHUB":      2,
		"PROVIDER_TYPE_TELEGRAM":    3,
		"PROVIDER_TYPE_GENERIC":     4,
	}
)

func (x ProviderType) Enum() *ProviderType {
	p := new(ProviderType)
	*p = x
	return p
}

func (x ProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_hookly_v1_common_proto_enumTypes[0].Descriptor()
}

func (ProviderType) Type() protoreflect.EnumType {
	return &file_hookly_v1_common_proto_enumTypes[0]
}

func (x ProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderType.Descriptor instead.
func (ProviderType) EnumDescriptor() ([]byte, []int) {
	return file_hookly_v1_common_proto_rawDescGZIP(), []int{0}
}

// Webhook delivery status
type WebhookStatus int32

const (
	WebhookStatus_WEBHOOK_STATUS_UNSPECIFIED WebhookStatus = 0
	WebhookStatus_WEBHOOK_STATUS_PENDING     WebhookStatus = 1
	WebhookStatus_WEBHOOK_STATUS_DELIVERED   WebhookStatus = 2
	WebhookStatus_WEBHOOK_STATUS_FAILED      WebhookStatus = 3
	WebhookStatus_WEBHOOK_STATUS_DEAD_LETTER WebhookStatus = 4
)

// Enum value maps for WebhookStatus.
var (
	WebhookStatus_name = map[int32]string{
		0: "WEBHOOK_STATUS_UNSPECIFIED",
		1: "WEBHOOK_STATUS_PENDING",
		2: "WEBHOOK_STATUS_DELIVERED",
		3: "WEBHOOK_STATUS_FAILED",
		4: "WEBHOOK_STATUS_DEAD_LETTER",
	}
	WebhookStatus_value = map[string]int32{
		"WEBHOOK_STATUS_UNSPECIFIED": 0,
		"WEBHOOK_STATUS_PENDING":     1,
		"WEBHOOK_STATUS_DELIVERED":   2,
		"WEBHOOK_STATUS_FAILED":      3,
		"WEBHOOK_STATUS_DEAD_LETTER": 4,
	}
)

func (x WebhookStatus) Enum() *WebhookStatus {
	p := new(WebhookStatus)
	*p = x
	return p
}

func (x WebhookStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebhookStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_hookly_v1_common_proto_enumTypes[1].Descriptor()
}

func (WebhookStatus) Type() protoreflect.EnumType {
	return &file_hookly_v1_common_proto_enumTypes[1]
}

func (x WebhookStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebhookStatus.Descriptor instead.
func (WebhookStatus) EnumDescriptor() ([]byte, []int) {
	return file_hookly_v1_common_proto_rawDescGZIP(), []int{1}
}

// Endpoint configuration
type Endpoint struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProviderType   ProviderType           `protobuf:"varint,3,opt,name=provider_type,json=providerType,proto3,enum=hookly.v1.ProviderType" json:"provider_type,omitempty"`
	DestinationUrl string                 `protobuf:"bytes,4,opt,name=destination_url,json=destinationUrl,proto3" json:"destination_url,omitempty"`
	Muted          bool                   `protobuf:"varint,5,opt,name=muted,proto3" json:"muted,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Note: signature_secret is not exposed in API responses
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_hookly_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_hookly_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Endpoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Endpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Endpoint) GetProviderType() ProviderType {
	if x != nil {
		return x.ProviderType
	}
	return ProviderType_PROVIDER_TYPE_UNSPECIFIED
}

func (x *Endpoint) GetDestinationUrl() string {
	if x != nil {
		return x.DestinationUrl
	}
	return ""
}

func (x *Endpoint) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *Endpoint) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Endpoint) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Webhook record
type Webhook struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EndpointId     string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	ReceivedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	Headers        map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Payload        []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	SignatureValid bool                   `protobuf:"varint,6,opt,name=signature_valid,json=signatureValid,proto3" json:"signature_valid,omitempty"`
	Status         WebhookStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=hookly.v1.WebhookStatus" json:"status,omitempty"`
	Attempts       int32                  `protobuf:"varint,8,opt,name=attempts,proto3" json:"attempts,omitempty"`
	LastAttemptAt  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_attempt_at,json=lastAttemptAt,proto3" json:"last_attempt_at,omitempty"`
	DeliveredAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,11,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Webhook) Reset() {
	*x = Webhook{}
	mi := &file_hookly_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Webhook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Webhook) ProtoMessage() {}

func (x *Webhook) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Webhook.ProtoReflect.Descriptor instead.
func (*Webhook) Descriptor() ([]byte, []int) {
	return file_hookly_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Webhook) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Webhook) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *Webhook) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *Webhook) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Webhook) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Webhook) GetSignatureValid() bool {
	if x != nil {
		return x.SignatureValid
	}
	return false
}

func (x *Webhook) GetStatus() WebhookStatus {
	if x != nil {
		return x.Status
	}
	return WebhookStatus_WEBHOOK_STATUS_UNSPECIFIED
}

func (x *Webhook) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Webhook) GetLastAttemptAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAttemptAt
	}
	return nil
}

func (x *Webhook) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

func (x *Webhook) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Pagination request parameters
type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_hookly_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_hookly_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *PaginationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Pagination response metadata
type PaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPageToken string                 `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_hookly_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_hookly_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *PaginationResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *PaginationResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// System status information
type SystemStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PendingCount         int32                  `protobuf:"varint,1,opt,name=pending_count,json=pendingCount,proto3" json:"pending_count,omitempty"`
	FailedCount          int32                  `protobuf:"varint,2,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	DeadLetterCount      int32                  `protobuf:"varint,3,opt,name=dead_letter_count,json=deadLetterCount,proto3" json:"dead_letter_count,omitempty"`
	HomeHubConnected     bool                   `protobuf:"varint,4,opt,name=home_hub_connected,json=homeHubConnected,proto3" json:"home_hub_connected,omitempty"`
	LastHomeHubHeartbeat *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_home_hub_heartbeat,json=lastHomeHubHeartbeat,proto3" json:"last_home_hub_heartbeat,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SystemStatus) Reset() {
	*x = SystemStatus{}
	mi := &file_hookly_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatus) ProtoMessage() {}

func (x *SystemStatus) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatus.ProtoReflect.Descriptor instead.
func (*SystemStatus) Descriptor() ([]byte, []int) {
	return file_hookly_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *SystemStatus) GetPendingCount() int32 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

func (x *SystemStatus) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *SystemStatus) GetDeadLetterCount() int32 {
	if x != nil {
		return x.DeadLetterCount
	}
	return 0
}

func (x *SystemStatus) GetHomeHubConnected() bool {
	if x != nil {
		return x.HomeHubConnected
	}
	return false
}

func (x *SystemStatus) GetLastHomeHubHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHomeHubHeartbeat
	}
	return nil
}

var File_hookly_v1_common_proto protoreflect.FileDescriptor

const file_hookly_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x16hookly/v1/common.proto\x12\thookly.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x02\n" +
	"\bEndpoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12<\n" +
	"\rprovider_type\x18\x03 \x01(\x0e2\x17.hookly.v1.ProviderTypeR\fproviderType\x12'\n" +
	"\x0fdestination_url\x18\x04 \x01(\tR\x0edestinationUrl\x12\x14\n" +
	"\x05muted\x18\x05 \x01(\bR\x05muted\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa7\x04\n" +
	"\aWebhook\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12;\n" +
	"\vreceived_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x129\n" +
	"\aheaders\x18\x04 \x03(\v2\x1f.hookly.v1.Webhook.HeadersEntryR\aheaders\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12'\n" +
	"\x0fsignature_valid\x18\x06 \x01(\bR\x0esignatureValid\x120\n" +
	"\x06status\x18\a \x01(\x0e2\x18.hookly.v1.WebhookStatusR\x06status\x12\x1a\n" +
	"\battempts\x18\b \x01(\x05R\battempts\x12B\n" +
	"\x0flast_attempt_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\rlastAttemptAt\x12=\n" +
	"\fdelivered_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vdeliveredAt\x12#\n" +
	"\rerror_message\x18\v \x01(\tR\ferrorMessage\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x11PaginationRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"]\n" +
	"\x12PaginationResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x83\x02\n" +
	"\fSystemStatus\x12#\n" +
	"\rpending_count\x18\x01 \x01(\x05R\fpendingCount\x12!\n" +
	"\ffailed_count\x18\x02 \x01(\x05R\vfailedCount\x12*\n" +
	"\x11dead_letter_count\x18\x03 \x01(\x05R\x0fdeadLetterCount\x12,\n" +
	"\x12home_hub_connected\x18\x04 \x01(\bR\x10homeHubConnected\x12Q\n" +
	"\x17last_home_hub_heartbeat\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x14lastHomeHubHeartbeat*\x98\x01\n" +
	"\fProviderType\x12\x1d\n" +
	"\x19PROVIDER_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PROVIDER_TYPE_STRIPE\x10\x01\x12\x18\n" +
	"\x14PROVIDER_TYPE_GITHUB\x10\x02\x12\x1a\n" +
	"\x16PROVIDER_TYPE_TELEGRAM\x10\x03\x12\x19\n" +
	"\x15PROVIDER_TYPE_GENERIC\x10\x04*\xa4\x01\n" +
	"\rWebhookStatus\x12\x1e\n" +
	"\x1aWEBHOOK_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16WEBHOOK_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18WEBHOOK_STATUS_DELIVERED\x10\x02\x12\x19\n" +
	"\x15WEBHOOK_STATUS_FAILED\x10\x03\x12\x1e\n" +
	"\x1aWEBHOOK_STATUS_DEAD_LETTER\x10\x04B\x89\x01\n" +
	"\rcom.hookly.v1B\vCommonProtoP\x01Z&hookly/internal/api/hookly/v1;hooklyv1\xa2\x02\x03HXX\xaa\x02\tHookly.V1\xca\x02\tHookly\\V1\xe2\x02\x15Hookly\\V1\\GPBMetadata\xea\x02\n" +
	"Hookly::V1b\x06proto3"

var (
	file_hookly_v1_common_proto_rawDescOnce sync.Once
	file_hookly_v1_common_proto_rawDescData []byte
)

func file_hookly_v1_common_proto_rawDescGZIP() []byte {
	file_hookly_v1_common_proto_rawDescOnce.Do(func() {
		file_hookly_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hookly_v1_common_proto_rawDesc), len(file_hookly_v1_common_proto_rawDesc)))
	})
	return file_hookly_v1_common_proto_rawDescData
}

var file_hookly_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_hookly_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_hookly_v1_common_proto_goTypes = []any{
	(ProviderType)(0),             // 0: hookly.v1.ProviderType
	(WebhookStatus)(0),            // 1: hookly.v1.WebhookStatus
	(*Endpoint)(nil),              // 2: hookly.v1.Endpoint
	(*Webhook)(nil),               // 3: hookly.v1.Webhook
	(*PaginationRequest)(nil),     // 4: hookly.v1.PaginationRequest
	(*PaginationResponse)(nil),    // 5: hookly.v1.PaginationResponse
	(*SystemStatus)(nil),          // 6: hookly.v1.SystemStatus
	nil,                           // 7: hookly.v1.Webhook.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_hookly_v1_common_proto_depIdxs = []int32{
	0, // 0: hookly.v1.Endpoint.provider_type:type_name -> hookly.v1.ProviderType
	8, // 1: hookly.v1.Endpoint.created_at:type_name -> google.protobuf.Timestamp
	8, // 2: hookly.v1.Endpoint.updated_at:type_name -> google.protobuf.Timestamp
	8, // 3: hookly.v1.Webhook.received_at:type_name -> google.protobuf.Timestamp
	7, // 4: hookly.v1.Webhook.headers:type_name -> hookly.v1.Webhook.HeadersEntry
	1, // 5: hookly.v1.Webhook.status:type_name -> hookly.v1.WebhookStatus
	8, // 6: hookly.v1.Webhook.last_attempt_at:type_name -> google.protobuf.Timestamp
	8, // 7: hookly.v1.Webhook.delivered_at:type_name -> google.protobuf.Timestamp
	8, // 8: hookly.v1.SystemStatus.last_home_hub_heartbeat:type_name -> google.protobuf.Timestamp
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_hookly_v1_common_proto_init() }
func file_hookly_v1_common_proto_init() {
	if File_hookly_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hookly_v1_common_proto_rawDesc), len(file_hookly_v1_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hookly_v1_common_proto_goTypes,
		DependencyIndexes: file_hookly_v1_common_proto_depIdxs,
		EnumInfos:         file_hookly_v1_common_proto_enumTypes,
		MessageInfos:      file_hookly_v1_common_proto_msgTypes,
	}.Build()
	File_hookly_v1_common_proto = out.File
	file_hookly_v1_common_proto_goTypes = nil
	file_hookly_v1_common_proto_depIdxs = nil
}
