// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hookly/v1/edge.proto

package hooklyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEndpointRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ProviderType    ProviderType           `protobuf:"varint,2,opt,name=provider_type,json=providerType,proto3,enum=hookly.v1.ProviderType" json:"provider_type,omitempty"`
	SignatureSecret string                 `protobuf:"bytes,3,opt,name=signature_secret,json=signatureSecret,proto3" json:"signature_secret,omitempty"`
	DestinationUrl  string                 `protobuf:"bytes,4,opt,name=destination_url,json=destinationUrl,proto3" json:"destination_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateEndpointRequest) Reset() {
	*x = CreateEndpointRequest{}
	mi := &file_hookly_v1_edge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEndpointRequest) ProtoMessage() {}

func (x *CreateEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEndpointRequest.ProtoReflect.Descriptor instead.
func (*CreateEndpointRequest) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEndpointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEndpointRequest) GetProviderType() ProviderType {
	if x != nil {
		return x.ProviderType
	}
	return ProviderType_PROVIDER_TYPE_UNSPECIFIED
}

func (x *CreateEndpointRequest) GetSignatureSecret() string {
	if x != nil {
		return x.SignatureSecret
	}
	return ""
}

func (x *CreateEndpointRequest) GetDestinationUrl() string {
	if x != nil {
		return x.DestinationUrl
	}
	return ""
}

type CreateEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      *Endpoint              `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	WebhookUrl    string                 `protobuf:"bytes,2,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"` // Full URL for provider configuration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEndpointResponse) Reset() {
	*x = CreateEndpointResponse{}
	mi := &file_hookly_v1_edge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEndpointResponse) ProtoMessage() {}

func (x *CreateEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEndpointResponse.ProtoReflect.Descriptor instead.
func (*CreateEndpointResponse) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEndpointResponse) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *CreateEndpointResponse) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

type GetEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEndpointRequest) Reset() {
	*x = GetEndpointRequest{}
	mi := &file_hookly_v1_edge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndpointRequest) ProtoMessage() {}

func (x *GetEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndpointRequest.ProtoReflect.Descriptor instead.
func (*GetEndpointRequest) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{2}
}

func (x *GetEndpointRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      *Endpoint              `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	WebhookUrl    string                 `protobuf:"bytes,2,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEndpointResponse) Reset() {
	*x = GetEndpointResponse{}
	mi := &file_hookly_v1_edge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndpointResponse) ProtoMessage() {}

func (x *GetEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndpointResponse.ProtoReflect.Descriptor instead.
func (*GetEndpointResponse) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{3}
}

func (x *GetEndpointResponse) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *GetEndpointResponse) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

type ListEndpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpointsRequest) Reset() {
	*x = ListEndpointsRequest{}
	mi := &file_hookly_v1_edge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsRequest) ProtoMessage() {}

func (x *ListEndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsRequest.ProtoReflect.Descriptor instead.
func (*ListEndpointsRequest) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{4}
}

func (x *ListEndpointsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListEndpointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*Endpoint            `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpointsResponse) Reset() {
	*x = ListEndpointsResponse{}
	mi := &file_hookly_v1_edge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsResponse) ProtoMessage() {}

func (x *ListEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsResponse.ProtoReflect.Descriptor instead.
func (*ListEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{5}
}

func (x *ListEndpointsResponse) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *ListEndpointsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type UpdateEndpointRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	SignatureSecret *string                `protobuf:"bytes,3,opt,name=signature_secret,json=signatureSecret,proto3,oneof" json:"signature_secret,omitempty"`
	DestinationUrl  *string                `protobuf:"bytes,4,opt,name=destination_url,json=destinationUrl,proto3,oneof" json:"destination_url,omitempty"`
	Muted           *bool                  `protobuf:"varint,5,opt,name=muted,proto3,oneof" json:"muted,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateEndpointRequest) Reset() {
	*x = UpdateEndpointRequest{}
	mi := &file_hookly_v1_edge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEndpointRequest) ProtoMessage() {}

func (x *UpdateEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEndpointRequest.ProtoReflect.Descriptor instead.
func (*UpdateEndpointRequest) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEndpointRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEndpointRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateEndpointRequest) GetSignatureSecret() string {
	if x != nil && x.SignatureSecret != nil {
		return *x.SignatureSecret
	}
	return ""
}

func (x *UpdateEndpointRequest) GetDestinationUrl() string {
	if x != nil && x.DestinationUrl != nil {
		return *x.DestinationUrl
	}
	return ""
}

func (x *UpdateEndpointRequest) GetMuted() bool {
	if x != nil && x.Muted != nil {
		return *x.Muted
	}
	return false
}

type UpdateEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      *Endpoint              `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEndpointResponse) Reset() {
	*x = UpdateEndpointResponse{}
	mi := &file_hookly_v1_edge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEndpointResponse) ProtoMessage() {}

func (x *UpdateEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEndpointResponse.ProtoReflect.Descriptor instead.
func (*UpdateEndpointResponse) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateEndpointResponse) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type DeleteEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEndpointRequest) Reset() {
	*x = DeleteEndpointRequest{}
	mi := &file_hookly_v1_edge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEndpointRequest) ProtoMessage() {}

func (x *DeleteEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEndpointRequest.ProtoReflect.Descriptor instead.
func (*DeleteEndpointRequest) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteEndpointRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEndpointResponse) Reset() {
	*x = DeleteEndpointResponse{}
	mi := &file_hookly_v1_edge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEndpointResponse) ProtoMessage() {}

func (x *DeleteEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEndpointResponse.ProtoReflect.Descriptor instead.
func (*DeleteEndpointResponse) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{9}
}

type GetWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebhookRequest) Reset() {
	*x = GetWebhookRequest{}
	mi := &file_hookly_v1_edge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookRequest) ProtoMessage() {}

func (x *GetWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebhookRequest.ProtoReflect.Descriptor instead.
func (*GetWebhookRequest) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{10}
}

func (x *GetWebhookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webhook       *Webhook               `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebhookResponse) Reset() {
	*x = GetWebhookResponse{}
	mi := &file_hookly_v1_edge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookResponse) ProtoMessage() {}

func (x *GetWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebhookResponse.ProtoReflect.Descriptor instead.
func (*GetWebhookResponse) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{11}
}

func (x *GetWebhookResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

type ListWebhooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    *string                `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3,oneof" json:"endpoint_id,omitempty"`
	Status        *WebhookStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=hookly.v1.WebhookStatus,oneof" json:"status,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhooksRequest) Reset() {
	*x = ListWebhooksRequest{}
	mi := &file_hookly_v1_edge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhooksRequest) ProtoMessage() {}

func (x *ListWebhooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhooksRequest.ProtoReflect.Descriptor instead.
func (*ListWebhooksRequest) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{12}
}

func (x *ListWebhooksRequest) GetEndpointId() string {
	if x != nil && x.EndpointId != nil {
		return *x.EndpointId
	}
	return ""
}

func (x *ListWebhooksRequest) GetStatus() WebhookStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return WebhookStatus_WEBHOOK_STATUS_UNSPECIFIED
}

func (x *ListWebhooksRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListWebhooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webhooks      []*Webhook             `protobuf:"bytes,1,rep,name=webhooks,proto3" json:"webhooks,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhooksResponse) Reset() {
	*x = ListWebhooksResponse{}
	mi := &file_hookly_v1_edge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhooksResponse) ProtoMessage() {}

func (x *ListWebhooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhooksResponse.ProtoReflect.Descriptor instead.
func (*ListWebhooksResponse) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{13}
}

func (x *ListWebhooksResponse) GetWebhooks() []*Webhook {
	if x != nil {
		return x.Webhooks
	}
	return nil
}

func (x *ListWebhooksResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ReplayWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayWebhookRequest) Reset() {
	*x = ReplayWebhookRequest{}
	mi := &file_hookly_v1_edge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayWebhookRequest) ProtoMessage() {}

func (x *ReplayWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayWebhookRequest.ProtoReflect.Descriptor instead.
func (*ReplayWebhookRequest) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{14}
}

func (x *ReplayWebhookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReplayWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webhook       *Webhook               `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayWebhookResponse) Reset() {
	*x = ReplayWebhookResponse{}
	mi := &file_hookly_v1_edge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayWebhookResponse) ProtoMessage() {}

func (x *ReplayWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayWebhookResponse.ProtoReflect.Descriptor instead.
func (*ReplayWebhookResponse) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{15}
}

func (x *ReplayWebhookResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_hookly_v1_edge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{16}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *SystemStatus          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_hookly_v1_edge_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{17}
}

func (x *GetStatusResponse) GetStatus() *SystemStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsRequest) Reset() {
	*x = GetSettingsRequest{}
	mi := &file_hookly_v1_edge_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRequest) ProtoMessage() {}

func (x *GetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{18}
}

type GetSettingsResponse struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl                      string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	GithubAuthEnabled            bool                   `protobuf:"varint,2,opt,name=github_auth_enabled,json=githubAuthEnabled,proto3" json:"github_auth_enabled,omitempty"`
	TelegramNotificationsEnabled bool                   `protobuf:"varint,3,opt,name=telegram_notifications_enabled,json=telegramNotificationsEnabled,proto3" json:"telegram_notifications_enabled,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *GetSettingsResponse) Reset() {
	*x = GetSettingsResponse{}
	mi := &file_hookly_v1_edge_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsResponse) ProtoMessage() {}

func (x *GetSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_edge_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetSettingsResponse) Descriptor() ([]byte, []int) {
	return file_hookly_v1_edge_proto_rawDescGZIP(), []int{19}
}

func (x *GetSettingsResponse) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *GetSettingsResponse) GetGithubAuthEnabled() bool {
	if x != nil {
		return x.GithubAuthEnabled
	}
	return false
}

func (x *GetSettingsResponse) GetTelegramNotificationsEnabled() bool {
	if x != nil {
		return x.TelegramNotificationsEnabled
	}
	return false
}

var File_hookly_v1_edge_proto protoreflect.FileDescriptor

const file_hookly_v1_edge_proto_rawDesc = "" +
	"\n" +
	"\x14hookly/v1/edge.proto\x12\thookly.v1\x1a\x16hookly/v1/common.proto\"\xbd\x01\n" +
	"\x15CreateEndpointRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\rprovider_type\x18\x02 \x01(\x0e2\x17.hookly.v1.ProviderTypeR\fproviderType\x12)\n" +
	"\x10signature_secret\x18\x03 \x01(\tR\x0fsignatureSecret\x12'\n" +
	"\x0fdestination_url\x18\x04 \x01(\tR\x0edestinationUrl\"j\n" +
	"\x16CreateEndpointResponse\x12/\n" +
	"\bendpoint\x18\x01 \x01(\v2\x13.hookly.v1.EndpointR\bendpoint\x12\x1f\n" +
	"\vwebhook_url\x18\x02 \x01(\tR\n" +
	"webhookUrl\"$\n" +
	"\x12GetEndpointRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"g\n" +
	"\x13GetEndpointResponse\x12/\n" +
	"\bendpoint\x18\x01 \x01(\v2\x13.hookly.v1.EndpointR\bendpoint\x12\x1f\n" +
	"\vwebhook_url\x18\x02 \x01(\tR\n" +
	"webhookUrl\"T\n" +
	"\x14ListEndpointsRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.hookly.v1.PaginationRequestR\n" +
	"pagination\"\x89\x01\n" +
	"\x15ListEndpointsResponse\x121\n" +
	"\tendpoints\x18\x01 \x03(\v2\x13.hookly.v1.EndpointR\tendpoints\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.hookly.v1.PaginationResponseR\n" +
	"pagination\"\xf5\x01\n" +
	"\x15UpdateEndpointRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12.\n" +
	"\x10signature_secret\x18\x03 \x01(\tH\x01R\x0fsignatureSecret\x88\x01\x01\x12,\n" +
	"\x0fdestination_url\x18\x04 \x01(\tH\x02R\x0edestinationUrl\x88\x01\x01\x12\x19\n" +
	"\x05muted\x18\x05 \x01(\bH\x03R\x05muted\x88\x01\x01B\a\n" +
	"\x05_nameB\x13\n" +
	"\x11_signature_secretB\x12\n" +
	"\x10_destination_urlB\b\n" +
	"\x06_muted\"I\n" +
	"\x16UpdateEndpointResponse\x12/\n" +
	"\bendpoint\x18\x01 \x01(\v2\x13.hookly.v1.EndpointR\bendpoint\"'\n" +
	"\x15DeleteEndpointRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteEndpointResponse\"#\n" +
	"\x11GetWebhookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x12GetWebhookResponse\x12,\n" +
	"\awebhook\x18\x01 \x01(\v2\x12.hookly.v1.WebhookR\awebhook\"\xcb\x01\n" +
	"\x13ListWebhooksRequest\x12$\n" +
	"\vendpoint_id\x18\x01 \x01(\tH\x00R\n" +
	"endpointId\x88\x01\x01\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.hookly.v1.WebhookStatusH\x01R\x06status\x88\x01\x01\x12<\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1c.hookly.v1.PaginationRequestR\n" +
	"paginationB\x0e\n" +
	"\f_endpoint_idB\t\n" +
	"\a_status\"\x85\x01\n" +
	"\x14ListWebhooksResponse\x12.\n" +
	"\bwebhooks\x18\x01 \x03(\v2\x12.hookly.v1.WebhookR\bwebhooks\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.hookly.v1.PaginationResponseR\n" +
	"pagination\"&\n" +
	"\x14ReplayWebhookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x15ReplayWebhookResponse\x12,\n" +
	"\awebhook\x18\x01 \x01(\v2\x12.hookly.v1.WebhookR\awebhook\"\x12\n" +
	"\x10GetStatusRequest\"D\n" +
	"\x11GetStatusResponse\x12/\n" +
	"\x06status\x18\x01 \x01(\v2\x17.hookly.v1.SystemStatusR\x06status\"\x14\n" +
	"\x12GetSettingsRequest\"\xa6\x01\n" +
	"\x13GetSettingsResponse\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12.\n" +
	"\x13github_auth_enabled\x18\x02 \x01(\bR\x11githubAuthEnabled\x12D\n" +
	"\x1etelegram_notifications_enabled\x18\x03 \x01(\bR\x1ctelegramNotificationsEnabled2\xba\x06\n" +
	"\vEdgeService\x12U\n" +
	"\x0eCreateEndpoint\x12 .hookly.v1.CreateEndpointRequest\x1a!.hookly.v1.CreateEndpointResponse\x12L\n" +
	"\vGetEndpoint\x12\x1d.hookly.v1.GetEndpointRequest\x1a\x1e.hookly.v1.GetEndpointResponse\x12R\n" +
	"\rListEndpoints\x12\x1f.hookly.v1.ListEndpointsRequest\x1a .hookly.v1.ListEndpointsResponse\x12U\n" +
	"\x0eUpdateEndpoint\x12 .hookly.v1.UpdateEndpointRequest\x1a!.hookly.v1.UpdateEndpointResponse\x12U\n" +
	"\x0eDeleteEndpoint\x12 .hookly.v1.DeleteEndpointRequest\x1a!.hookly.v1.DeleteEndpointResponse\x12I\n" +
	"\n" +
	"GetWebhook\x12\x1c.hookly.v1.GetWebhookRequest\x1a\x1d.hookly.v1.GetWebhookResponse\x12O\n" +
	"\fListWebhooks\x12\x1e.hookly.v1.ListWebhooksRequest\x1a\x1f.hookly.v1.ListWebhooksResponse\x12R\n" +
	"\rReplayWebhook\x12\x1f.hookly.v1.ReplayWebhookRequest\x1a .hookly.v1.ReplayWebhookResponse\x12F\n" +
	"\tGetStatus\x12\x1b.hookly.v1.GetStatusRequest\x1a\x1c.hookly.v1.GetStatusResponse\x12L\n" +
	"\vGetSettings\x12\x1d.hookly.v1.GetSettingsRequest\x1a\x1e.hookly.v1.GetSettingsResponseB\x90\x01\n" +
	"\rcom.hookly.v1B\tEdgeProtoP\x01Z/hooks.dx314.com/internal/api/hookly/v1;hooklyv1\xa2\x02\x03HXX\xaa\x02\tHookly.V1\xca\x02\tHookly\\V1\xe2\x02\x15Hookly\\V1\\GPBMetadata\xea\x02\n" +
	"Hookly::V1b\x06proto3"

var (
	file_hookly_v1_edge_proto_rawDescOnce sync.Once
	file_hookly_v1_edge_proto_rawDescData []byte
)

func file_hookly_v1_edge_proto_rawDescGZIP() []byte {
	file_hookly_v1_edge_proto_rawDescOnce.Do(func() {
		file_hookly_v1_edge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hookly_v1_edge_proto_rawDesc), len(file_hookly_v1_edge_proto_rawDesc)))
	})
	return file_hookly_v1_edge_proto_rawDescData
}

var file_hookly_v1_edge_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_hookly_v1_edge_proto_goTypes = []any{
	(*CreateEndpointRequest)(nil),  // 0: hookly.v1.CreateEndpointRequest
	(*CreateEndpointResponse)(nil), // 1: hookly.v1.CreateEndpointResponse
	(*GetEndpointRequest)(nil),     // 2: hookly.v1.GetEndpointRequest
	(*GetEndpointResponse)(nil),    // 3: hookly.v1.GetEndpointResponse
	(*ListEndpointsRequest)(nil),   // 4: hookly.v1.ListEndpointsRequest
	(*ListEndpointsResponse)(nil),  // 5: hookly.v1.ListEndpointsResponse
	(*UpdateEndpointRequest)(nil),  // 6: hookly.v1.UpdateEndpointRequest
	(*UpdateEndpointResponse)(nil), // 7: hookly.v1.UpdateEndpointResponse
	(*DeleteEndpointRequest)(nil),  // 8: hookly.v1.DeleteEndpointRequest
	(*DeleteEndpointResponse)(nil), // 9: hookly.v1.DeleteEndpointResponse
	(*GetWebhookRequest)(nil),      // 10: hookly.v1.GetWebhookRequest
	(*GetWebhookResponse)(nil),     // 11: hookly.v1.GetWebhookResponse
	(*ListWebhooksRequest)(nil),    // 12: hookly.v1.ListWebhooksRequest
	(*ListWebhooksResponse)(nil),   // 13: hookly.v1.ListWebhooksResponse
	(*ReplayWebhookRequest)(nil),   // 14: hookly.v1.ReplayWebhookRequest
	(*ReplayWebhookResponse)(nil),  // 15: hookly.v1.ReplayWebhookResponse
	(*GetStatusRequest)(nil),       // 16: hookly.v1.GetStatusRequest
	(*GetStatusResponse)(nil),      // 17: hookly.v1.GetStatusResponse
	(*GetSettingsRequest)(nil),     // 18: hookly.v1.GetSettingsRequest
	(*GetSettingsResponse)(nil),    // 19: hookly.v1.GetSettingsResponse
	(ProviderType)(0),              // 20: hookly.v1.ProviderType
	(*Endpoint)(nil),               // 21: hookly.v1.Endpoint
	(*PaginationRequest)(nil),      // 22: hookly.v1.PaginationRequest
	(*PaginationResponse)(nil),     // 23: hookly.v1.PaginationResponse
	(*Webhook)(nil),                // 24: hookly.v1.Webhook
	(WebhookStatus)(0),             // 25: hookly.v1.WebhookStatus
	(*SystemStatus)(nil),           // 26: hookly.v1.SystemStatus
}
var file_hookly_v1_edge_proto_depIdxs = []int32{
	20, // 0: hookly.v1.CreateEndpointRequest.provider_type:type_name -> hookly.v1.ProviderType
	21, // 1: hookly.v1.CreateEndpointResponse.endpoint:type_name -> hookly.v1.Endpoint
	21, // 2: hookly.v1.GetEndpointResponse.endpoint:type_name -> hookly.v1.Endpoint
	22, // 3: hookly.v1.ListEndpointsRequest.pagination:type_name -> hookly.v1.PaginationRequest
	21, // 4: hookly.v1.ListEndpointsResponse.endpoints:type_name -> hookly.v1.Endpoint
	23, // 5: hookly.v1.ListEndpointsResponse.pagination:type_name -> hookly.v1.PaginationResponse
	21, // 6: hookly.v1.UpdateEndpointResponse.endpoint:type_name -> hookly.v1.Endpoint
	24, // 7: hookly.v1.GetWebhookResponse.webhook:type_name -> hookly.v1.Webhook
	25, // 8: hookly.v1.ListWebhooksRequest.status:type_name -> hookly.v1.WebhookStatus
	22, // 9: hookly.v1.ListWebhooksRequest.pagination:type_name -> hookly.v1.PaginationRequest
	24, // 10: hookly.v1.ListWebhooksResponse.webhooks:type_name -> hookly.v1.Webhook
	23, // 11: hookly.v1.ListWebhooksResponse.pagination:type_name -> hookly.v1.PaginationResponse
	24, // 12: hookly.v1.ReplayWebhookResponse.webhook:type_name -> hookly.v1.Webhook
	26, // 13: hookly.v1.GetStatusResponse.status:type_name -> hookly.v1.SystemStatus
	0,  // 14: hookly.v1.EdgeService.CreateEndpoint:input_type -> hookly.v1.CreateEndpointRequest
	2,  // 15: hookly.v1.EdgeService.GetEndpoint:input_type -> hookly.v1.GetEndpointRequest
	4,  // 16: hookly.v1.EdgeService.ListEndpoints:input_type -> hookly.v1.ListEndpointsRequest
	6,  // 17: hookly.v1.EdgeService.UpdateEndpoint:input_type -> hookly.v1.UpdateEndpointRequest
	8,  // 18: hookly.v1.EdgeService.DeleteEndpoint:input_type -> hookly.v1.DeleteEndpointRequest
	10, // 19: hookly.v1.EdgeService.GetWebhook:input_type -> hookly.v1.GetWebhookRequest
	12, // 20: hookly.v1.EdgeService.ListWebhooks:input_type -> hookly.v1.ListWebhooksRequest
	14, // 21: hookly.v1.EdgeService.ReplayWebhook:input_type -> hookly.v1.ReplayWebhookRequest
	16, // 22: hookly.v1.EdgeService.GetStatus:input_type -> hookly.v1.GetStatusRequest
	18, // 23: hookly.v1.EdgeService.GetSettings:input_type -> hookly.v1.GetSettingsRequest
	1,  // 24: hookly.v1.EdgeService.CreateEndpoint:output_type -> hookly.v1.CreateEndpointResponse
	3,  // 25: hookly.v1.EdgeService.GetEndpoint:output_type -> hookly.v1.GetEndpointResponse
	5,  // 26: hookly.v1.EdgeService.ListEndpoints:output_type -> hookly.v1.ListEndpointsResponse
	7,  // 27: hookly.v1.EdgeService.UpdateEndpoint:output_type -> hookly.v1.UpdateEndpointResponse
	9,  // 28: hookly.v1.EdgeService.DeleteEndpoint:output_type -> hookly.v1.DeleteEndpointResponse
	11, // 29: hookly.v1.EdgeService.GetWebhook:output_type -> hookly.v1.GetWebhookResponse
	13, // 30: hookly.v1.EdgeService.ListWebhooks:output_type -> hookly.v1.ListWebhooksResponse
	15, // 31: hookly.v1.EdgeService.ReplayWebhook:output_type -> hookly.v1.ReplayWebhookResponse
	17, // 32: hookly.v1.EdgeService.GetStatus:output_type -> hookly.v1.GetStatusResponse
	19, // 33: hookly.v1.EdgeService.GetSettings:output_type -> hookly.v1.GetSettingsResponse
	24, // [24:34] is the sub-list for method output_type
	14, // [14:24] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_hookly_v1_edge_proto_init() }
func file_hookly_v1_edge_proto_init() {
	if File_hookly_v1_edge_proto != nil {
		return
	}
	file_hookly_v1_common_proto_init()
	file_hookly_v1_edge_proto_msgTypes[6].OneofWrappers = []any{}
	file_hookly_v1_edge_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hookly_v1_edge_proto_rawDesc), len(file_hookly_v1_edge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hookly_v1_edge_proto_goTypes,
		DependencyIndexes: file_hookly_v1_edge_proto_depIdxs,
		MessageInfos:      file_hookly_v1_edge_proto_msgTypes,
	}.Build()
	File_hookly_v1_edge_proto = out.File
	file_hookly_v1_edge_proto_goTypes = nil
	file_hookly_v1_edge_proto_depIdxs = nil
}
