// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: hookly/v1/relay.proto

package hooklyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages from home-hub to edge
type StreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*StreamRequest_Connect
	//	*StreamRequest_Ack
	//	*StreamRequest_Heartbeat
	//	*StreamRequest_HttpResponse
	Message       isStreamRequest_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_hookly_v1_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_hookly_v1_relay_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetMessage() isStreamRequest_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StreamRequest) GetConnect() *ConnectRequest {
	if x != nil {
		if x, ok := x.Message.(*StreamRequest_Connect); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *StreamRequest) GetAck() *DeliveryAck {
	if x != nil {
		if x, ok := x.Message.(*StreamRequest_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *StreamRequest) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*StreamRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *StreamRequest) GetHttpResponse() *HttpResponse {
	if x != nil {
		if x, ok := x.Message.(*StreamRequest_HttpResponse); ok {
			return x.HttpResponse
		}
	}
	return nil
}

type isStreamRequest_Message interface {
	isStreamRequest_Message()
}

type StreamRequest_Connect struct {
	Connect *ConnectRequest `protobuf:"bytes,1,opt,name=connect,proto3,oneof"`
}

type StreamRequest_Ack struct {
	Ack *DeliveryAck `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type StreamRequest_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type StreamRequest_HttpResponse struct {
	HttpResponse *HttpResponse `protobuf:"bytes,4,opt,name=http_response,json=httpResponse,proto3,oneof"` // Answer to an HttpRequest (proxy)
}

func (*StreamRequest_Connect) isStreamRequest_Message() {}

func (*StreamRequest_Ack) isStreamRequest_Message() {}

func (*StreamRequest_Heartbeat) isStreamRequest_Message() {}

func (*StreamRequest_HttpResponse) isStreamRequest_Message() {}

// Messages from edge to home-hub
type StreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*StreamResponse_ConnectResponse
	//	*StreamResponse_Webhook
	//	*StreamResponse_Heartbeat
	//	*StreamResponse_HttpRequest
	Message       isStreamResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_hookly_v1_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_hookly_v1_relay_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResponse) GetMessage() isStreamResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StreamResponse) GetConnectResponse() *ConnectResponse {
	if x != nil {
		if x, ok := x.Message.(*StreamResponse_ConnectResponse); ok {
			return x.ConnectResponse
		}
	}
	return nil
}

func (x *StreamResponse) GetWebhook() *WebhookEnvelope {
	if x != nil {
		if x, ok := x.Message.(*StreamResponse_Webhook); ok {
			return x.Webhook
		}
	}
	return nil
}

func (x *StreamResponse) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*StreamResponse_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *StreamResponse) GetHttpRequest() *HttpRequest {
	if x != nil {
		if x, ok := x.Message.(*StreamResponse_HttpRequest); ok {
			return x.HttpRequest
		}
	}
	return nil
}

type isStreamResponse_Message interface {
	isStreamResponse_Message()
}

type StreamResponse_ConnectResponse struct {
	ConnectResponse *ConnectResponse `protobuf:"bytes,1,opt,name=connect_response,json=connectResponse,proto3,oneof"`
}

type StreamResponse_Webhook struct {
	Webhook *WebhookEnvelope `protobuf:"bytes,2,opt,name=webhook,proto3,oneof"`
}

type StreamResponse_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type StreamResponse_HttpRequest struct {
	HttpRequest *HttpRequest `protobuf:"bytes,4,opt,name=http_request,json=httpRequest,proto3,oneof"` // Only sent to hubs with the "proxy" capability
}

func (*StreamResponse_ConnectResponse) isStreamResponse_Message() {}

func (*StreamResponse_Webhook) isStreamResponse_Message() {}

func (*StreamResponse_Heartbeat) isStreamResponse_Message() {}

func (*StreamResponse_HttpRequest) isStreamResponse_Message() {}

// Initial connection request with authentication
type ConnectRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	HubId       string                 `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	Token       string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                                // Bearer token from CLI login
	EndpointIds []string               `protobuf:"bytes,3,rep,name=endpoint_ids,json=endpointIds,proto3" json:"endpoint_ids,omitempty"` // Endpoints this hub handles
	// Optional features this hub understands. Hubs that predate a feature omit it.
	//
	//	"fanout" - one envelope per (webhook, destination); acks echo delivery_id.
	//	"proxy"  - understands HttpRequest / HttpResponse (reverse proxy).
	//
	// Hubs without "fanout" are only sent each endpoint's primary destination.
	// (4 is skipped: it was endpoint_ids before bearer-token auth.)
	Capabilities []string `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Names of the local services this hub reverse-proxies (the `proxies:`
	// section of hookly.yaml). The edge serves /p/{hub_id}/{name}/* for each
	// and never sends an HttpRequest for a name that is not listed here.
	Proxies       []string `protobuf:"bytes,6,rep,name=proxies,proto3" json:"proxies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_hookly_v1_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_hookly_v1_relay_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *ConnectRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConnectRequest) GetEndpointIds() []string {
	if x != nil {
		return x.EndpointIds
	}
	return nil
}

func (x *ConnectRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ConnectRequest) GetProxies() []string {
	if x != nil {
		return x.Proxies
	}
	return nil
}

// Connection response
type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_hookly_v1_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_hookly_v1_relay_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Heartbeat for connection health monitoring
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_hookly_v1_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_hookly_v1_relay_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Webhook envelope for delivery to home network
type WebhookEnvelope struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EndpointId     string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	DestinationUrl string                 `protobuf:"bytes,3,opt,name=destination_url,json=destinationUrl,proto3" json:"destination_url,omitempty"`
	ReceivedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	Headers        map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Payload        []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Attempt        int32                  `protobuf:"varint,7,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// Fan-out: one envelope is sent per (webhook, destination). Older edges leave
	// these empty, older hubs ignore them.
	DeliveryId         string `protobuf:"bytes,8,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"` // Echo in DeliveryAck.delivery_id
	DestinationId      string `protobuf:"bytes,9,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	DestinationName    string `protobuf:"bytes,10,opt,name=destination_name,json=destinationName,proto3" json:"destination_name,omitempty"`           // Key for per-destination overrides in hookly.yaml
	DestinationPrimary bool   `protobuf:"varint,11,opt,name=destination_primary,json=destinationPrimary,proto3" json:"destination_primary,omitempty"` // True for the endpoint's first destination
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WebhookEnvelope) Reset() {
	*x = WebhookEnvelope{}
	mi := &file_hookly_v1_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEnvelope) ProtoMessage() {}

func (x *WebhookEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEnvelope.ProtoReflect.Descriptor instead.
func (*WebhookEnvelope) Descriptor() ([]byte, []int) {
	return file_hookly_v1_relay_proto_rawDescGZIP(), []int{5}
}

func (x *WebhookEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebhookEnvelope) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *WebhookEnvelope) GetDestinationUrl() string {
	if x != nil {
		return x.DestinationUrl
	}
	return ""
}

func (x *WebhookEnvelope) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *WebhookEnvelope) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *WebhookEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebhookEnvelope) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *WebhookEnvelope) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *WebhookEnvelope) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

func (x *WebhookEnvelope) GetDestinationName() string {
	if x != nil {
		return x.DestinationName
	}
	return ""
}

func (x *WebhookEnvelope) GetDestinationPrimary() bool {
	if x != nil {
		return x.DestinationPrimary
	}
	return false
}

// Delivery acknowledgment from home-hub
type DeliveryAck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WebhookId        string                 `protobuf:"bytes,1,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	Success          bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	StatusCode       int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	PermanentFailure bool                   `protobuf:"varint,5,opt,name=permanent_failure,json=permanentFailure,proto3" json:"permanent_failure,omitempty"` // true for 4xx, don't retry
	// Echoed from WebhookEnvelope. Hubs that predate fan-out leave these empty and
	// the edge falls back to the webhook's primary (or only pending) delivery.
	DeliveryId    string `protobuf:"bytes,6,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	DestinationId string `protobuf:"bytes,7,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryAck) Reset() {
	*x = DeliveryAck{}
	mi := &file_hookly_v1_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAck) ProtoMessage() {}

func (x *DeliveryAck) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAck.ProtoReflect.Descriptor instead.
func (*DeliveryAck) Descriptor() ([]byte, []int) {
	return file_hookly_v1_relay_proto_rawDescGZIP(), []int{6}
}

func (x *DeliveryAck) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

func (x *DeliveryAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeliveryAck) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeliveryAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DeliveryAck) GetPermanentFailure() bool {
	if x != nil {
		return x.PermanentFailure
	}
	return false
}

func (x *DeliveryAck) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *DeliveryAck) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

// HttpHeader is one header line. Headers repeat (Set-Cookie), so this is a
// list rather than a map.
type HttpHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpHeader) Reset() {
	*x = HttpHeader{}
	mi := &file_hookly_v1_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpHeader) ProtoMessage() {}

func (x *HttpHeader) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpHeader.ProtoReflect.Descriptor instead.
func (*HttpHeader) Descriptor() ([]byte, []int) {
	return file_hookly_v1_relay_proto_rawDescGZIP(), []int{7}
}

func (x *HttpHeader) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HttpHeader) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// HttpRequest is a synchronous HTTP request the edge received at
// /p/{hub_id}/{proxy}/... and forwards to the hub's local service. The hub
// answers with an HttpResponse carrying the same request_id.
type HttpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Proxy         string                 `protobuf:"bytes,2,opt,name=proxy,proto3" json:"proxy,omitempty"` // Name from ConnectRequest.proxies
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`                         // Already stripped of /p/{hub_id}/{proxy}; starts with "/"
	RawQuery      string                 `protobuf:"bytes,5,opt,name=raw_query,json=rawQuery,proto3" json:"raw_query,omitempty"` // Without the "?"
	Headers       []*HttpHeader          `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty"`                   // Hop-by-hop headers removed; X-Forwarded-* added
	Body          []byte                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_hookly_v1_relay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_relay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_hookly_v1_relay_proto_rawDescGZIP(), []int{8}
}

func (x *HttpRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HttpRequest) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetRawQuery() string {
	if x != nil {
		return x.RawQuery
	}
	return ""
}

func (x *HttpRequest) GetHeaders() []*HttpHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// HttpResponse is the local service's answer to an HttpRequest. When error is
// set the other fields are ignored and the edge answers 502.
type HttpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Headers       []*HttpHeader          `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_hookly_v1_relay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_relay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_hookly_v1_relay_proto_rawDescGZIP(), []int{9}
}

func (x *HttpResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HttpResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HttpResponse) GetHeaders() []*HttpHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_hookly_v1_relay_proto protoreflect.FileDescriptor

const file_hookly_v1_relay_proto_rawDesc = "" +
	"\n" +
	"\x15hookly/v1/relay.proto\x12\thookly.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf3\x01\n" +
	"\rStreamRequest\x125\n" +
	"\aconnect\x18\x01 \x01(\v2\x19.hookly.v1.ConnectRequestH\x00R\aconnect\x12*\n" +
	"\x03ack\x18\x02 \x01(\v2\x16.hookly.v1.DeliveryAckH\x00R\x03ack\x124\n" +
	"\theartbeat\x18\x03 \x01(\v2\x14.hookly.v1.HeartbeatH\x00R\theartbeat\x12>\n" +
	"\rhttp_response\x18\x04 \x01(\v2\x17.hookly.v1.HttpResponseH\x00R\fhttpResponseB\t\n" +
	"\amessage\"\x8f\x02\n" +
	"\x0eStreamResponse\x12G\n" +
	"\x10connect_response\x18\x01 \x01(\v2\x1a.hookly.v1.ConnectResponseH\x00R\x0fconnectResponse\x126\n" +
	"\awebhook\x18\x02 \x01(\v2\x1a.hookly.v1.WebhookEnvelopeH\x00R\awebhook\x124\n" +
	"\theartbeat\x18\x03 \x01(\v2\x14.hookly.v1.HeartbeatH\x00R\theartbeat\x12;\n" +
	"\fhttp_request\x18\x04 \x01(\v2\x16.hookly.v1.HttpRequestH\x00R\vhttpRequestB\t\n" +
	"\amessage\"\x9e\x01\n" +
	"\x0eConnectRequest\x12\x15\n" +
	"\x06hub_id\x18\x01 \x01(\tR\x05hubId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12!\n" +
	"\fendpoint_ids\x18\x03 \x03(\tR\vendpointIds\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12\x18\n" +
	"\aproxies\x18\x06 \x03(\tR\aproxies\"A\n" +
	"\x0fConnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xff\x03\n" +
	"\x0fWebhookEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12'\n" +
	"\x0fdestination_url\x18\x03 \x01(\tR\x0edestinationUrl\x12;\n" +
	"\vreceived_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12A\n" +
	"\aheaders\x18\x05 \x03(\v2'.hookly.v1.WebhookEnvelope.HeadersEntryR\aheaders\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x18\n" +
	"\aattempt\x18\a \x01(\x05R\aattempt\x12\x1f\n" +
	"\vdelivery_id\x18\b \x01(\tR\n" +
	"deliveryId\x12%\n" +
	"\x0edestination_id\x18\t \x01(\tR\rdestinationId\x12)\n" +
	"\x10destination_name\x18\n" +
	" \x01(\tR\x0fdestinationName\x12/\n" +
	"\x13destination_primary\x18\v \x01(\bR\x12destinationPrimary\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x02\n" +
	"\vDeliveryAck\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x01 \x01(\tR\twebhookId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12+\n" +
	"\x11permanent_failure\x18\x05 \x01(\bR\x10permanentFailure\x12\x1f\n" +
	"\vdelivery_id\x18\x06 \x01(\tR\n" +
	"deliveryId\x12%\n" +
	"\x0edestination_id\x18\a \x01(\tR\rdestinationId\"6\n" +
	"\n" +
	"HttpHeader\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xd0\x01\n" +
	"\vHttpRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05proxy\x18\x02 \x01(\tR\x05proxy\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1b\n" +
	"\traw_query\x18\x05 \x01(\tR\brawQuery\x12/\n" +
	"\aheaders\x18\x06 \x03(\v2\x15.hookly.v1.HttpHeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\a \x01(\fR\x04body\"\xa0\x01\n" +
	"\fHttpResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12/\n" +
	"\aheaders\x18\x03 \x03(\v2\x15.hookly.v1.HttpHeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error2Q\n" +
	"\fRelayService\x12A\n" +
	"\x06Stream\x12\x18.hookly.v1.StreamRequest\x1a\x19.hookly.v1.StreamResponse(\x010\x01B\x91\x01\n" +
	"\rcom.hookly.v1B\n" +
	"RelayProtoP\x01Z/hooks.dx314.com/internal/api/hookly/v1;hooklyv1\xa2\x02\x03HXX\xaa\x02\tHookly.V1\xca\x02\tHookly\\V1\xe2\x02\x15Hookly\\V1\\GPBMetadata\xea\x02\n" +
	"Hookly::V1b\x06proto3"

var (
	file_hookly_v1_relay_proto_rawDescOnce sync.Once
	file_hookly_v1_relay_proto_rawDescData []byte
)

func file_hookly_v1_relay_proto_rawDescGZIP() []byte {
	file_hookly_v1_relay_proto_rawDescOnce.Do(func() {
		file_hookly_v1_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hookly_v1_relay_proto_rawDesc), len(file_hookly_v1_relay_proto_rawDesc)))
	})
	return file_hookly_v1_relay_proto_rawDescData
}

var file_hookly_v1_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_hookly_v1_relay_proto_goTypes = []any{
	(*StreamRequest)(nil),         // 0: hookly.v1.StreamRequest
	(*StreamResponse)(nil),        // 1: hookly.v1.StreamResponse
	(*ConnectRequest)(nil),        // 2: hookly.v1.ConnectRequest
	(*ConnectResponse)(nil),       // 3: hookly.v1.ConnectResponse
	(*Heartbeat)(nil),             // 4: hookly.v1.Heartbeat
	(*WebhookEnvelope)(nil),       // 5: hookly.v1.WebhookEnvelope
	(*DeliveryAck)(nil),           // 6: hookly.v1.DeliveryAck
	(*HttpHeader)(nil),            // 7: hookly.v1.HttpHeader
	(*HttpRequest)(nil),           // 8: hookly.v1.HttpRequest
	(*HttpResponse)(nil),          // 9: hookly.v1.HttpResponse
	nil,                           // 10: hookly.v1.WebhookEnvelope.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_hookly_v1_relay_proto_depIdxs = []int32{
	2,  // 0: hookly.v1.StreamRequest.connect:type_name -> hookly.v1.ConnectRequest
	6,  // 1: hookly.v1.StreamRequest.ack:type_name -> hookly.v1.DeliveryAck
	4,  // 2: hookly.v1.StreamRequest.heartbeat:type_name -> hookly.v1.Heartbeat
	9,  // 3: hookly.v1.StreamRequest.http_response:type_name -> hookly.v1.HttpResponse
	3,  // 4: hookly.v1.StreamResponse.connect_response:type_name -> hookly.v1.ConnectResponse
	5,  // 5: hookly.v1.StreamResponse.webhook:type_name -> hookly.v1.WebhookEnvelope
	4,  // 6: hookly.v1.StreamResponse.heartbeat:type_name -> hookly.v1.Heartbeat
	8,  // 7: hookly.v1.StreamResponse.http_request:type_name -> hookly.v1.HttpRequest
	11, // 8: hookly.v1.WebhookEnvelope.received_at:type_name -> google.protobuf.Timestamp
	10, // 9: hookly.v1.WebhookEnvelope.headers:type_name -> hookly.v1.WebhookEnvelope.HeadersEntry
	7,  // 10: hookly.v1.HttpRequest.headers:type_name -> hookly.v1.HttpHeader
	7,  // 11: hookly.v1.HttpResponse.headers:type_name -> hookly.v1.HttpHeader
	0,  // 12: hookly.v1.RelayService.Stream:input_type -> hookly.v1.StreamRequest
	1,  // 13: hookly.v1.RelayService.Stream:output_type -> hookly.v1.StreamResponse
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_hookly_v1_relay_proto_init() }
func file_hookly_v1_relay_proto_init() {
	if File_hookly_v1_relay_proto != nil {
		return
	}
	file_hookly_v1_relay_proto_msgTypes[0].OneofWrappers = []any{
		(*StreamRequest_Connect)(nil),
		(*StreamRequest_Ack)(nil),
		(*StreamRequest_Heartbeat)(nil),
		(*StreamRequest_HttpResponse)(nil),
	}
	file_hookly_v1_relay_proto_msgTypes[1].OneofWrappers = []any{
		(*StreamResponse_ConnectResponse)(nil),
		(*StreamResponse_Webhook)(nil),
		(*StreamResponse_Heartbeat)(nil),
		(*StreamResponse_HttpRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hookly_v1_relay_proto_rawDesc), len(file_hookly_v1_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hookly_v1_relay_proto_goTypes,
		DependencyIndexes: file_hookly_v1_relay_proto_depIdxs,
		MessageInfos:      file_hookly_v1_relay_proto_msgTypes,
	}.Build()
	File_hookly_v1_relay_proto = out.File
	file_hookly_v1_relay_proto_goTypes = nil
	file_hookly_v1_relay_proto_depIdxs = nil
}
