// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hookly/v1/relay.proto

package hooklyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages from home-hub to edge
type StreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*StreamRequest_Connect
	//	*StreamRequest_Ack
	//	*StreamRequest_Heartbeat
	Message       isStreamRequest_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_hookly_v1_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_hookly_v1_relay_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetMessage() isStreamRequest_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StreamRequest) GetConnect() *ConnectRequest {
	if x != nil {
		if x, ok := x.Message.(*StreamRequest_Connect); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *StreamRequest) GetAck() *DeliveryAck {
	if x != nil {
		if x, ok := x.Message.(*StreamRequest_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *StreamRequest) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*StreamRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isStreamRequest_Message interface {
	isStreamRequest_Message()
}

type StreamRequest_Connect struct {
	Connect *ConnectRequest `protobuf:"bytes,1,opt,name=connect,proto3,oneof"`
}

type StreamRequest_Ack struct {
	Ack *DeliveryAck `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type StreamRequest_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*StreamRequest_Connect) isStreamRequest_Message() {}

func (*StreamRequest_Ack) isStreamRequest_Message() {}

func (*StreamRequest_Heartbeat) isStreamRequest_Message() {}

// Messages from edge to home-hub
type StreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*StreamResponse_ConnectResponse
	//	*StreamResponse_Webhook
	//	*StreamResponse_Heartbeat
	Message       isStreamResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_hookly_v1_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_hookly_v1_relay_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResponse) GetMessage() isStreamResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StreamResponse) GetConnectResponse() *ConnectResponse {
	if x != nil {
		if x, ok := x.Message.(*StreamResponse_ConnectResponse); ok {
			return x.ConnectResponse
		}
	}
	return nil
}

func (x *StreamResponse) GetWebhook() *WebhookEnvelope {
	if x != nil {
		if x, ok := x.Message.(*StreamResponse_Webhook); ok {
			return x.Webhook
		}
	}
	return nil
}

func (x *StreamResponse) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*StreamResponse_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isStreamResponse_Message interface {
	isStreamResponse_Message()
}

type StreamResponse_ConnectResponse struct {
	ConnectResponse *ConnectResponse `protobuf:"bytes,1,opt,name=connect_response,json=connectResponse,proto3,oneof"`
}

type StreamResponse_Webhook struct {
	Webhook *WebhookEnvelope `protobuf:"bytes,2,opt,name=webhook,proto3,oneof"`
}

type StreamResponse_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*StreamResponse_ConnectResponse) isStreamResponse_Message() {}

func (*StreamResponse_Webhook) isStreamResponse_Message() {}

func (*StreamResponse_Heartbeat) isStreamResponse_Message() {}

// Initial connection request with authentication
type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HubId         string                 `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                       // Unix timestamp
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                        // HMAC-SHA256(hub_id + timestamp, secret)
	EndpointIds   []string               `protobuf:"bytes,4,rep,name=endpoint_ids,json=endpointIds,proto3" json:"endpoint_ids,omitempty"` // Endpoints this hub handles
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_hookly_v1_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_hookly_v1_relay_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *ConnectRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ConnectRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ConnectRequest) GetEndpointIds() []string {
	if x != nil {
		return x.EndpointIds
	}
	return nil
}

// Connection response
type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_hookly_v1_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_hookly_v1_relay_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Heartbeat for connection health monitoring
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_hookly_v1_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_hookly_v1_relay_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Webhook envelope for delivery to home network
type WebhookEnvelope struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EndpointId     string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	DestinationUrl string                 `protobuf:"bytes,3,opt,name=destination_url,json=destinationUrl,proto3" json:"destination_url,omitempty"`
	ReceivedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	Headers        map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Payload        []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Attempt        int32                  `protobuf:"varint,7,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WebhookEnvelope) Reset() {
	*x = WebhookEnvelope{}
	mi := &file_hookly_v1_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEnvelope) ProtoMessage() {}

func (x *WebhookEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEnvelope.ProtoReflect.Descriptor instead.
func (*WebhookEnvelope) Descriptor() ([]byte, []int) {
	return file_hookly_v1_relay_proto_rawDescGZIP(), []int{5}
}

func (x *WebhookEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebhookEnvelope) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *WebhookEnvelope) GetDestinationUrl() string {
	if x != nil {
		return x.DestinationUrl
	}
	return ""
}

func (x *WebhookEnvelope) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *WebhookEnvelope) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *WebhookEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebhookEnvelope) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

// Delivery acknowledgment from home-hub
type DeliveryAck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WebhookId        string                 `protobuf:"bytes,1,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	Success          bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	StatusCode       int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	PermanentFailure bool                   `protobuf:"varint,5,opt,name=permanent_failure,json=permanentFailure,proto3" json:"permanent_failure,omitempty"` // true for 4xx, don't retry
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeliveryAck) Reset() {
	*x = DeliveryAck{}
	mi := &file_hookly_v1_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAck) ProtoMessage() {}

func (x *DeliveryAck) ProtoReflect() protoreflect.Message {
	mi := &file_hookly_v1_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAck.ProtoReflect.Descriptor instead.
func (*DeliveryAck) Descriptor() ([]byte, []int) {
	return file_hookly_v1_relay_proto_rawDescGZIP(), []int{6}
}

func (x *DeliveryAck) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

func (x *DeliveryAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeliveryAck) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeliveryAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DeliveryAck) GetPermanentFailure() bool {
	if x != nil {
		return x.PermanentFailure
	}
	return false
}

var File_hookly_v1_relay_proto protoreflect.FileDescriptor

const file_hookly_v1_relay_proto_rawDesc = "" +
	"\n" +
	"\x15hookly/v1/relay.proto\x12\thookly.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x01\n" +
	"\rStreamRequest\x125\n" +
	"\aconnect\x18\x01 \x01(\v2\x19.hookly.v1.ConnectRequestH\x00R\aconnect\x12*\n" +
	"\x03ack\x18\x02 \x01(\v2\x16.hookly.v1.DeliveryAckH\x00R\x03ack\x124\n" +
	"\theartbeat\x18\x03 \x01(\v2\x14.hookly.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\amessage\"\xd2\x01\n" +
	"\x0eStreamResponse\x12G\n" +
	"\x10connect_response\x18\x01 \x01(\v2\x1a.hookly.v1.ConnectResponseH\x00R\x0fconnectResponse\x126\n" +
	"\awebhook\x18\x02 \x01(\v2\x1a.hookly.v1.WebhookEnvelopeH\x00R\awebhook\x124\n" +
	"\theartbeat\x18\x03 \x01(\v2\x14.hookly.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\amessage\"\x86\x01\n" +
	"\x0eConnectRequest\x12\x15\n" +
	"\x06hub_id\x18\x01 \x01(\tR\x05hubId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12!\n" +
	"\fendpoint_ids\x18\x04 \x03(\tR\vendpointIds\"A\n" +
	"\x0fConnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xdb\x02\n" +
	"\x0fWebhookEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12'\n" +
	"\x0fdestination_url\x18\x03 \x01(\tR\x0edestinationUrl\x12;\n" +
	"\vreceived_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12A\n" +
	"\aheaders\x18\x05 \x03(\v2'.hookly.v1.WebhookEnvelope.HeadersEntryR\aheaders\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x18\n" +
	"\aattempt\x18\a \x01(\x05R\aattempt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x01\n" +
	"\vDeliveryAck\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x01 \x01(\tR\twebhookId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12+\n" +
	"\x11permanent_failure\x18\x05 \x01(\bR\x10permanentFailure2Q\n" +
	"\fRelayService\x12A\n" +
	"\x06Stream\x12\x18.hookly.v1.StreamRequest\x1a\x19.hookly.v1.StreamResponse(\x010\x01B\x91\x01\n" +
	"\rcom.hookly.v1B\n" +
	"RelayProtoP\x01Z/hooks.dx314.com/internal/api/hookly/v1;hooklyv1\xa2\x02\x03HXX\xaa\x02\tHookly.V1\xca\x02\tHookly\\V1\xe2\x02\x15Hookly\\V1\\GPBMetadata\xea\x02\n" +
	"Hookly::V1b\x06proto3"

var (
	file_hookly_v1_relay_proto_rawDescOnce sync.Once
	file_hookly_v1_relay_proto_rawDescData []byte
)

func file_hookly_v1_relay_proto_rawDescGZIP() []byte {
	file_hookly_v1_relay_proto_rawDescOnce.Do(func() {
		file_hookly_v1_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hookly_v1_relay_proto_rawDesc), len(file_hookly_v1_relay_proto_rawDesc)))
	})
	return file_hookly_v1_relay_proto_rawDescData
}

var file_hookly_v1_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_hookly_v1_relay_proto_goTypes = []any{
	(*StreamRequest)(nil),         // 0: hookly.v1.StreamRequest
	(*StreamResponse)(nil),        // 1: hookly.v1.StreamResponse
	(*ConnectRequest)(nil),        // 2: hookly.v1.ConnectRequest
	(*ConnectResponse)(nil),       // 3: hookly.v1.ConnectResponse
	(*Heartbeat)(nil),             // 4: hookly.v1.Heartbeat
	(*WebhookEnvelope)(nil),       // 5: hookly.v1.WebhookEnvelope
	(*DeliveryAck)(nil),           // 6: hookly.v1.DeliveryAck
	nil,                           // 7: hookly.v1.WebhookEnvelope.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_hookly_v1_relay_proto_depIdxs = []int32{
	2, // 0: hookly.v1.StreamRequest.connect:type_name -> hookly.v1.ConnectRequest
	6, // 1: hookly.v1.StreamRequest.ack:type_name -> hookly.v1.DeliveryAck
	4, // 2: hookly.v1.StreamRequest.heartbeat:type_name -> hookly.v1.Heartbeat
	3, // 3: hookly.v1.StreamResponse.connect_response:type_name -> hookly.v1.ConnectResponse
	5, // 4: hookly.v1.StreamResponse.webhook:type_name -> hookly.v1.WebhookEnvelope
	4, // 5: hookly.v1.StreamResponse.heartbeat:type_name -> hookly.v1.Heartbeat
	8, // 6: hookly.v1.WebhookEnvelope.received_at:type_name -> google.protobuf.Timestamp
	7, // 7: hookly.v1.WebhookEnvelope.headers:type_name -> hookly.v1.WebhookEnvelope.HeadersEntry
	0, // 8: hookly.v1.RelayService.Stream:input_type -> hookly.v1.StreamRequest
	1, // 9: hookly.v1.RelayService.Stream:output_type -> hookly.v1.StreamResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_hookly_v1_relay_proto_init() }
func file_hookly_v1_relay_proto_init() {
	if File_hookly_v1_relay_proto != nil {
		return
	}
	file_hookly_v1_relay_proto_msgTypes[0].OneofWrappers = []any{
		(*StreamRequest_Connect)(nil),
		(*StreamRequest_Ack)(nil),
		(*StreamRequest_Heartbeat)(nil),
	}
	file_hookly_v1_relay_proto_msgTypes[1].OneofWrappers = []any{
		(*StreamResponse_ConnectResponse)(nil),
		(*StreamResponse_Webhook)(nil),
		(*StreamResponse_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hookly_v1_relay_proto_rawDesc), len(file_hookly_v1_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hookly_v1_relay_proto_goTypes,
		DependencyIndexes: file_hookly_v1_relay_proto_depIdxs,
		MessageInfos:      file_hookly_v1_relay_proto_msgTypes,
	}.Build()
	File_hookly_v1_relay_proto = out.File
	file_hookly_v1_relay_proto_goTypes = nil
	file_hookly_v1_relay_proto_depIdxs = nil
}
