package cli

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"strconv"
	"strings"

	"connectrpc.com/connect"

	hooklyv1 "hooks.dx314.com/internal/api/hookly/v1"
)

// WizardConfig holds the configuration generated by the wizard.
type WizardConfig struct {
	EdgeURL     string
	EndpointID  string
	Destination string
}

// RunWizard runs the interactive init wizard.
func RunWizard(client *Client, creds *Credentials) (*WizardConfig, error) {
	fmt.Printf("Logged in as %s (%s)\n\n", creds.Username, creds.EdgeURL)

	// List endpoints
	resp, err := client.Edge.ListEndpoints(context.Background(), connect.NewRequest(&hooklyv1.ListEndpointsRequest{}))
	if err != nil {
		return nil, fmt.Errorf("list endpoints: %w", err)
	}

	endpoints := resp.Msg.Endpoints
	justCreated := false
	if len(endpoints) == 0 {
		fmt.Println("No endpoints found. Let's create one.")
		endpoint, err := createEndpointWizard(client)
		if err != nil {
			return nil, err
		}
		endpoints = []*hooklyv1.Endpoint{endpoint}
		justCreated = true
	}

	// Display endpoints
	fmt.Println("Available endpoints:")
	for i, ep := range endpoints {
		fmt.Printf("  %d. %s (%s)\n", i+1, ep.Name, ep.Id)
	}
	fmt.Println()

	// Select endpoint
	selectedIndex := 0
	if len(endpoints) > 1 {
		fmt.Print("Select endpoint [1]: ")
		input := readLine()
		if input != "" {
			idx, err := strconv.Atoi(input)
			if err != nil || idx < 1 || idx > len(endpoints) {
				return nil, fmt.Errorf("invalid selection: %s", input)
			}
			selectedIndex = idx - 1
		}
	}

	selectedEndpoint := endpoints[selectedIndex]
	fmt.Printf("\nSelected: %s (%s)\n", selectedEndpoint.Name, selectedEndpoint.Id)

	// Get destination URL (skip if we just created this endpoint)
	destination := selectedEndpoint.DestinationUrl
	if !justCreated {
		fmt.Printf("\nDestination URL [%s]: ", destination)
		destInput := readLine()
		if destInput != "" {
			destination = destInput
		}
	}

	return &WizardConfig{
		EdgeURL:     creds.EdgeURL,
		EndpointID:  selectedEndpoint.Id,
		Destination: destination,
	}, nil
}

// GenerateConfigYAML generates hookly.yaml content from wizard config.
func GenerateConfigYAML(cfg *WizardConfig) string {
	return fmt.Sprintf(`# Hookly configuration
edge_url: "%s"
# hub_id is optional - auto-generated from hostname if not set

endpoints:
  - id: "%s"
    destination: "%s"
`, cfg.EdgeURL, cfg.EndpointID, cfg.Destination)
}

// readLine reads a line from stdin, trimming whitespace.
func readLine() string {
	reader := bufio.NewReader(os.Stdin)
	line, _ := reader.ReadString('\n')
	return strings.TrimSpace(line)
}

var signatureFormats = []struct {
	name  string
	value hooklyv1.ProviderType
}{
	{"Stripe", hooklyv1.ProviderType_PROVIDER_TYPE_STRIPE},
	{"GitHub", hooklyv1.ProviderType_PROVIDER_TYPE_GITHUB},
	{"Telegram", hooklyv1.ProviderType_PROVIDER_TYPE_TELEGRAM},
	{"Generic (HMAC-SHA256)", hooklyv1.ProviderType_PROVIDER_TYPE_GENERIC},
}

func createEndpointWizard(client *Client) (*hooklyv1.Endpoint, error) {
	// Get endpoint name
	fmt.Print("Endpoint name: ")
	name := readLine()
	if name == "" {
		return nil, fmt.Errorf("endpoint name is required")
	}

	// Get destination URL first (more intuitive flow)
	fmt.Print("\nDestination URL (e.g., http://localhost:8080/webhook): ")
	destinationURL := readLine()
	if destinationURL == "" {
		return nil, fmt.Errorf("destination URL is required")
	}

	// Ask about signature verification
	fmt.Print("\nRequires signature verification? (y/N): ")
	verifyInput := strings.ToLower(readLine())

	providerType := hooklyv1.ProviderType_PROVIDER_TYPE_GENERIC
	if verifyInput == "y" || verifyInput == "yes" {
		fmt.Println("\nSignature format:")
		for i, sf := range signatureFormats {
			fmt.Printf("  %d. %s\n", i+1, sf.name)
		}
		fmt.Print("Select format [1]: ")
		formatInput := readLine()
		formatIndex := 0
		if formatInput != "" {
			idx, err := strconv.Atoi(formatInput)
			if err != nil || idx < 1 || idx > len(signatureFormats) {
				return nil, fmt.Errorf("invalid selection: %s", formatInput)
			}
			formatIndex = idx - 1
		}
		providerType = signatureFormats[formatIndex].value
	}

	// Create endpoint
	fmt.Println("\nCreating endpoint...")
	createResp, err := client.Edge.CreateEndpoint(context.Background(), connect.NewRequest(&hooklyv1.CreateEndpointRequest{
		Name:           name,
		ProviderType:   providerType,
		DestinationUrl: destinationURL,
	}))
	if err != nil {
		return nil, fmt.Errorf("create endpoint: %w", err)
	}

	fmt.Printf("Created endpoint: %s (%s)\n\n", createResp.Msg.Endpoint.Name, createResp.Msg.Endpoint.Id)
	return createResp.Msg.Endpoint, nil
}
