package cli

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"

	"connectrpc.com/connect"

	hooklyv1 "hooks.dx314.com/internal/api/hookly/v1"
)

// WizardConfig holds the configuration generated by the wizard.
type WizardConfig struct {
	EdgeURL     string
	HubID       string
	EndpointID  string
	Destination string
}

// RunWizard runs the interactive init wizard.
func RunWizard(client *Client, creds *Credentials) (*WizardConfig, error) {
	fmt.Printf("Logged in as %s (%s)\n\n", creds.Username, creds.EdgeURL)

	// List endpoints
	resp, err := client.Edge.ListEndpoints(nil, connect.NewRequest(&hooklyv1.ListEndpointsRequest{}))
	if err != nil {
		return nil, fmt.Errorf("list endpoints: %w", err)
	}

	endpoints := resp.Msg.Endpoints
	if len(endpoints) == 0 {
		fmt.Println("No endpoints found.")
		fmt.Println("Create an endpoint in the web UI first, then run 'hookly init' again.")
		return nil, nil
	}

	// Display endpoints
	fmt.Println("Available endpoints:")
	for i, ep := range endpoints {
		fmt.Printf("  %d. %s (%s)\n", i+1, ep.Name, ep.Id)
	}
	fmt.Println()

	// Select endpoint
	selectedIndex := 0
	if len(endpoints) > 1 {
		fmt.Print("Select endpoint [1]: ")
		input := readLine()
		if input != "" {
			idx, err := strconv.Atoi(input)
			if err != nil || idx < 1 || idx > len(endpoints) {
				return nil, fmt.Errorf("invalid selection: %s", input)
			}
			selectedIndex = idx - 1
		}
	}

	selectedEndpoint := endpoints[selectedIndex]
	fmt.Printf("\nSelected: %s (%s)\n", selectedEndpoint.Name, selectedEndpoint.Id)

	// Get destination URL
	defaultDest := selectedEndpoint.DestinationUrl
	fmt.Printf("\nDestination URL [%s]: ", defaultDest)
	destInput := readLine()
	destination := defaultDest
	if destInput != "" {
		destination = destInput
	}

	// Get hub ID
	defaultHubID := fmt.Sprintf("%s-dev", creds.Username)
	fmt.Printf("Hub ID [%s]: ", defaultHubID)
	hubIDInput := readLine()
	hubID := defaultHubID
	if hubIDInput != "" {
		hubID = hubIDInput
	}

	return &WizardConfig{
		EdgeURL:     creds.EdgeURL,
		HubID:       hubID,
		EndpointID:  selectedEndpoint.Id,
		Destination: destination,
	}, nil
}

// GenerateConfigYAML generates hookly.yaml content from wizard config.
func GenerateConfigYAML(cfg *WizardConfig) string {
	return fmt.Sprintf(`# Hookly configuration
edge_url: "%s"
secret: "YOUR_HOME_HUB_SECRET"
hub_id: "%s"

endpoints:
  - id: "%s"
    destination: "%s"
`, cfg.EdgeURL, cfg.HubID, cfg.EndpointID, cfg.Destination)
}

// readLine reads a line from stdin, trimming whitespace.
func readLine() string {
	reader := bufio.NewReader(os.Stdin)
	line, _ := reader.ReadString('\n')
	return strings.TrimSpace(line)
}
