// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: deliveries.sql

package db

import (
	"context"
	"database/sql"
)

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO deliveries (id, webhook_id, destination_id, status, attempts, created_at)
VALUES (?, ?, ?, 'pending', 0, datetime('now'))
RETURNING seq, id, webhook_id, destination_id, status, attempts, last_attempt_at, delivered_at, error_message, notification_sent, created_at
`

type CreateDeliveryParams struct {
	ID            string `json:"id"`
	WebhookID     string `json:"webhook_id"`
	DestinationID string `json:"destination_id"`
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, createDelivery, arg.ID, arg.WebhookID, arg.DestinationID)
	var i Delivery
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.WebhookID,
		&i.DestinationID,
		&i.Status,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.DeliveredAt,
		&i.ErrorMessage,
		&i.NotificationSent,
		&i.CreatedAt,
	)
	return i, err
}

const getDelivery = `-- name: GetDelivery :one
SELECT seq, id, webhook_id, destination_id, status, attempts, last_attempt_at, delivered_at, error_message, notification_sent, created_at FROM deliveries WHERE id = ?
`

func (q *Queries) GetDelivery(ctx context.Context, id string) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, getDelivery, id)
	var i Delivery
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.WebhookID,
		&i.DestinationID,
		&i.Status,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.DeliveredAt,
		&i.ErrorMessage,
		&i.NotificationSent,
		&i.CreatedAt,
	)
	return i, err
}

const getDeliveryByWebhookAndDestination = `-- name: GetDeliveryByWebhookAndDestination :one
SELECT seq, id, webhook_id, destination_id, status, attempts, last_attempt_at, delivered_at, error_message, notification_sent, created_at FROM deliveries WHERE webhook_id = ? AND destination_id = ?
`

type GetDeliveryByWebhookAndDestinationParams struct {
	WebhookID     string `json:"webhook_id"`
	DestinationID string `json:"destination_id"`
}

func (q *Queries) GetDeliveryByWebhookAndDestination(ctx context.Context, arg GetDeliveryByWebhookAndDestinationParams) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryByWebhookAndDestination, arg.WebhookID, arg.DestinationID)
	var i Delivery
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.WebhookID,
		&i.DestinationID,
		&i.Status,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.DeliveredAt,
		&i.ErrorMessage,
		&i.NotificationSent,
		&i.CreatedAt,
	)
	return i, err
}

const getDeliveryForNotification = `-- name: GetDeliveryForNotification :one
SELECT d.id AS delivery_id, d.attempts, d.error_message, d.notification_sent,
       w.id AS webhook_id, w.endpoint_id, w.received_at,
       e.user_id, e.name AS endpoint_name, dest.name AS destination_name, dest.url AS destination_url
FROM deliveries d
JOIN destinations dest ON d.destination_id = dest.id
JOIN webhooks w ON d.webhook_id = w.id
JOIN endpoints e ON w.endpoint_id = e.id
WHERE d.id = ?
`

type GetDeliveryForNotificationRow struct {
	DeliveryID       string         `json:"delivery_id"`
	Attempts         int64          `json:"attempts"`
	ErrorMessage     sql.NullString `json:"error_message"`
	NotificationSent int64          `json:"notification_sent"`
	WebhookID        string         `json:"webhook_id"`
	EndpointID       string         `json:"endpoint_id"`
	ReceivedAt       string         `json:"received_at"`
	UserID           string         `json:"user_id"`
	EndpointName     string         `json:"endpoint_name"`
	DestinationName  string         `json:"destination_name"`
	DestinationUrl   string         `json:"destination_url"`
}

func (q *Queries) GetDeliveryForNotification(ctx context.Context, id string) (GetDeliveryForNotificationRow, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryForNotification, id)
	var i GetDeliveryForNotificationRow
	err := row.Scan(
		&i.DeliveryID,
		&i.Attempts,
		&i.ErrorMessage,
		&i.NotificationSent,
		&i.WebhookID,
		&i.EndpointID,
		&i.ReceivedAt,
		&i.UserID,
		&i.EndpointName,
		&i.DestinationName,
		&i.DestinationUrl,
	)
	return i, err
}

const getDestinationDeliveryStats = `-- name: GetDestinationDeliveryStats :many
SELECT d.destination_id,
       CAST(SUM(CASE WHEN d.status = 'pending' THEN 1 ELSE 0 END) AS INTEGER) AS pending_count,
       CAST(SUM(CASE WHEN d.status = 'delivered' THEN 1 ELSE 0 END) AS INTEGER) AS delivered_count,
       CAST(SUM(CASE WHEN d.status = 'failed' THEN 1 ELSE 0 END) AS INTEGER) AS failed_count,
       CAST(SUM(CASE WHEN d.status = 'dead_letter' THEN 1 ELSE 0 END) AS INTEGER) AS dead_letter_count,
       CAST(COALESCE(MAX(d.delivered_at), '') AS TEXT) AS last_delivered_at
FROM deliveries d
JOIN destinations dest ON d.destination_id = dest.id
WHERE dest.endpoint_id = ?
GROUP BY d.destination_id
`

type GetDestinationDeliveryStatsRow struct {
	DestinationID   string `json:"destination_id"`
	PendingCount    int64  `json:"pending_count"`
	DeliveredCount  int64  `json:"delivered_count"`
	FailedCount     int64  `json:"failed_count"`
	DeadLetterCount int64  `json:"dead_letter_count"`
	LastDeliveredAt string `json:"last_delivered_at"`
}

// Delivery counts per destination of an endpoint.
func (q *Queries) GetDestinationDeliveryStats(ctx context.Context, endpointID string) ([]GetDestinationDeliveryStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDestinationDeliveryStats, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDestinationDeliveryStatsRow{}
	for rows.Next() {
		var i GetDestinationDeliveryStatsRow
		if err := rows.Scan(
			&i.DestinationID,
			&i.PendingCount,
			&i.DeliveredCount,
			&i.FailedCount,
			&i.DeadLetterCount,
			&i.LastDeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDestinationLastError = `-- name: GetDestinationLastError :one
SELECT CAST(COALESCE(error_message, '') AS TEXT) AS error_message
FROM deliveries
WHERE destination_id = ? AND status != 'delivered' AND error_message IS NOT NULL
ORDER BY last_attempt_at DESC, seq DESC
LIMIT 1
`

// Most recent error of a destination's undelivered deliveries.
func (q *Queries) GetDestinationLastError(ctx context.Context, destinationID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getDestinationLastError, destinationID)
	var error_message string
	err := row.Scan(&error_message)
	return error_message, err
}

const getDispatchableDeliveries = `-- name: GetDispatchableDeliveries :many
SELECT d.id AS delivery_id, d.seq, d.attempts, d.destination_id,
       dest.name AS destination_name, dest.url AS destination_url,
       w.id AS webhook_id, w.endpoint_id, w.received_at, w.headers, w.payload
FROM deliveries d
JOIN destinations dest ON d.destination_id = dest.id
JOIN webhooks w ON d.webhook_id = w.id
JOIN endpoints e ON w.endpoint_id = e.id
WHERE d.status = 'pending'
  AND e.muted = 0
  AND dest.enabled = 1
  -- Respect backoff: either never attempted, or backoff delay has passed (1s -> 1h)
  AND (
    d.last_attempt_at IS NULL
    OR datetime(d.last_attempt_at, '+' || MIN(1 << MIN(d.attempts, 12), 3600) || ' seconds') <= datetime('now')
  )
  -- In-order delivery: nothing older is still pending for this destination
  AND NOT EXISTS (
    SELECT 1 FROM deliveries d2
    WHERE d2.destination_id = d.destination_id
      AND d2.status = 'pending'
      AND d2.seq < d.seq
  )
ORDER BY d.seq ASC
LIMIT ?
`

type GetDispatchableDeliveriesRow struct {
	DeliveryID      string `json:"delivery_id"`
	Seq             int64  `json:"seq"`
	Attempts        int64  `json:"attempts"`
	DestinationID   string `json:"destination_id"`
	DestinationName string `json:"destination_name"`
	DestinationUrl  string `json:"destination_url"`
	WebhookID       string `json:"webhook_id"`
	EndpointID      string `json:"endpoint_id"`
	ReceivedAt      string `json:"received_at"`
	Headers         string `json:"headers"`
	Payload         []byte `json:"payload"`
}

// Deliveries ready to be sent, respecting backoff and in-order delivery per
// (endpoint, destination): only the oldest pending delivery of each destination
// is returned, so one failing destination never holds back another.
func (q *Queries) GetDispatchableDeliveries(ctx context.Context, limit int64) ([]GetDispatchableDeliveriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getDispatchableDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDispatchableDeliveriesRow{}
	for rows.Next() {
		var i GetDispatchableDeliveriesRow
		if err := rows.Scan(
			&i.DeliveryID,
			&i.Seq,
			&i.Attempts,
			&i.DestinationID,
			&i.DestinationName,
			&i.DestinationUrl,
			&i.WebhookID,
			&i.EndpointID,
			&i.ReceivedAt,
			&i.Headers,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnnotifiedDeadLetterDeliveries = `-- name: GetUnnotifiedDeadLetterDeliveries :many
SELECT d.id AS delivery_id, d.attempts, d.error_message,
       w.id AS webhook_id, w.endpoint_id, w.received_at,
       e.user_id, e.name AS endpoint_name, dest.name AS destination_name, dest.url AS destination_url
FROM deliveries d
JOIN destinations dest ON d.destination_id = dest.id
JOIN webhooks w ON d.webhook_id = w.id
JOIN endpoints e ON w.endpoint_id = e.id
WHERE d.status = 'dead_letter'
  AND d.notification_sent = 0
ORDER BY d.seq DESC
LIMIT ?
`

type GetUnnotifiedDeadLetterDeliveriesRow struct {
	DeliveryID      string         `json:"delivery_id"`
	Attempts        int64          `json:"attempts"`
	ErrorMessage    sql.NullString `json:"error_message"`
	WebhookID       string         `json:"webhook_id"`
	EndpointID      string         `json:"endpoint_id"`
	ReceivedAt      string         `json:"received_at"`
	UserID          string         `json:"user_id"`
	EndpointName    string         `json:"endpoint_name"`
	DestinationName string         `json:"destination_name"`
	DestinationUrl  string         `json:"destination_url"`
}

// Dead-lettered deliveries that haven't been notified yet.
func (q *Queries) GetUnnotifiedDeadLetterDeliveries(ctx context.Context, limit int64) ([]GetUnnotifiedDeadLetterDeliveriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnnotifiedDeadLetterDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnnotifiedDeadLetterDeliveriesRow{}
	for rows.Next() {
		var i GetUnnotifiedDeadLetterDeliveriesRow
		if err := rows.Scan(
			&i.DeliveryID,
			&i.Attempts,
			&i.ErrorMessage,
			&i.WebhookID,
			&i.EndpointID,
			&i.ReceivedAt,
			&i.UserID,
			&i.EndpointName,
			&i.DestinationName,
			&i.DestinationUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveriesByWebhook = `-- name: ListDeliveriesByWebhook :many
SELECT d.seq, d.id, d.webhook_id, d.destination_id, d.status, d.attempts, d.last_attempt_at, d.delivered_at, d.error_message, d.notification_sent, d.created_at, dest.name AS destination_name, dest.url AS destination_url, dest.enabled AS destination_enabled
FROM deliveries d
JOIN destinations dest ON d.destination_id = dest.id
WHERE d.webhook_id = ?
ORDER BY dest.position ASC, dest.created_at ASC, dest.id ASC
`

type ListDeliveriesByWebhookRow struct {
	Seq                int64          `json:"seq"`
	ID                 string         `json:"id"`
	WebhookID          string         `json:"webhook_id"`
	DestinationID      string         `json:"destination_id"`
	Status             string         `json:"status"`
	Attempts           int64          `json:"attempts"`
	LastAttemptAt      sql.NullString `json:"last_attempt_at"`
	DeliveredAt        sql.NullString `json:"delivered_at"`
	ErrorMessage       sql.NullString `json:"error_message"`
	NotificationSent   int64          `json:"notification_sent"`
	CreatedAt          string         `json:"created_at"`
	DestinationName    string         `json:"destination_name"`
	DestinationUrl     string         `json:"destination_url"`
	DestinationEnabled int64          `json:"destination_enabled"`
}

// Deliveries of a webhook with destination info, primary destination first.
func (q *Queries) ListDeliveriesByWebhook(ctx context.Context, webhookID string) ([]ListDeliveriesByWebhookRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeliveriesByWebhook, webhookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeliveriesByWebhookRow{}
	for rows.Next() {
		var i ListDeliveriesByWebhookRow
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.WebhookID,
			&i.DestinationID,
			&i.Status,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.DeliveredAt,
			&i.ErrorMessage,
			&i.NotificationSent,
			&i.CreatedAt,
			&i.DestinationName,
			&i.DestinationUrl,
			&i.DestinationEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredPendingDeliveries = `-- name: ListExpiredPendingDeliveries :many
SELECT d.id, d.webhook_id
FROM deliveries d
JOIN webhooks w ON d.webhook_id = w.id
WHERE d.status = 'pending'
  AND w.received_at < datetime('now', '-7 days')
`

type ListExpiredPendingDeliveriesRow struct {
	ID        string `json:"id"`
	WebhookID string `json:"webhook_id"`
}

// Pending deliveries whose webhook is older than the 7 day delivery window.
func (q *Queries) ListExpiredPendingDeliveries(ctx context.Context) ([]ListExpiredPendingDeliveriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredPendingDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredPendingDeliveriesRow{}
	for rows.Next() {
		var i ListExpiredPendingDeliveriesRow
		if err := rows.Scan(&i.ID, &i.WebhookID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDeliveriesByWebhook = `-- name: ListPendingDeliveriesByWebhook :many
SELECT d.seq, d.id, d.webhook_id, d.destination_id, d.status, d.attempts, d.last_attempt_at, d.delivered_at, d.error_message, d.notification_sent, d.created_at
FROM deliveries d
JOIN destinations dest ON d.destination_id = dest.id
WHERE d.webhook_id = ? AND d.status = 'pending'
ORDER BY dest.position ASC, dest.created_at ASC, dest.id ASC
`

func (q *Queries) ListPendingDeliveriesByWebhook(ctx context.Context, webhookID string) ([]Delivery, error) {
	rows, err := q.db.QueryContext(ctx, listPendingDeliveriesByWebhook, webhookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Delivery{}
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.WebhookID,
			&i.DestinationID,
			&i.Status,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.DeliveredAt,
			&i.ErrorMessage,
			&i.NotificationSent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookIDsByDestination = `-- name: ListWebhookIDsByDestination :many
SELECT webhook_id FROM deliveries WHERE destination_id = ?
`

// Webhooks that have a delivery for this destination (to re-derive their status).
func (q *Queries) ListWebhookIDsByDestination(ctx context.Context, destinationID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookIDsByDestination, destinationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var webhook_id string
		if err := rows.Scan(&webhook_id); err != nil {
			return nil, err
		}
		items = append(items, webhook_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryDeadLetter = `-- name: MarkDeliveryDeadLetter :exec
UPDATE deliveries
SET status = 'dead_letter'
WHERE id = ? AND status = 'pending'
`

func (q *Queries) MarkDeliveryDeadLetter(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markDeliveryDeadLetter, id)
	return err
}

const markDeliveryDelivered = `-- name: MarkDeliveryDelivered :one
UPDATE deliveries
SET status = 'delivered',
    attempts = attempts + 1,
    last_attempt_at = datetime('now'),
    delivered_at = datetime('now'),
    error_message = NULL
WHERE id = ? AND status = 'pending'
RETURNING seq, id, webhook_id, destination_id, status, attempts, last_attempt_at, delivered_at, error_message, notification_sent, created_at
`

func (q *Queries) MarkDeliveryDelivered(ctx context.Context, id string) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, markDeliveryDelivered, id)
	var i Delivery
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.WebhookID,
		&i.DestinationID,
		&i.Status,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.DeliveredAt,
		&i.ErrorMessage,
		&i.NotificationSent,
		&i.CreatedAt,
	)
	return i, err
}

const markDeliveryFailed = `-- name: MarkDeliveryFailed :one
UPDATE deliveries
SET status = 'failed',
    attempts = attempts + 1,
    last_attempt_at = datetime('now'),
    error_message = ?
WHERE id = ? AND status = 'pending'
RETURNING seq, id, webhook_id, destination_id, status, attempts, last_attempt_at, delivered_at, error_message, notification_sent, created_at
`

type MarkDeliveryFailedParams struct {
	ErrorMessage sql.NullString `json:"error_message"`
	ID           string         `json:"id"`
}

// Permanent failure (4xx response) - no retry.
func (q *Queries) MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, markDeliveryFailed, arg.ErrorMessage, arg.ID)
	var i Delivery
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.WebhookID,
		&i.DestinationID,
		&i.Status,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.DeliveredAt,
		&i.ErrorMessage,
		&i.NotificationSent,
		&i.CreatedAt,
	)
	return i, err
}

const markDeliveryNotificationSent = `-- name: MarkDeliveryNotificationSent :exec
UPDATE deliveries
SET notification_sent = 1
WHERE id = ?
`

// Mark notification as sent to prevent spam.
func (q *Queries) MarkDeliveryNotificationSent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markDeliveryNotificationSent, id)
	return err
}

const recordDeliveryAttempt = `-- name: RecordDeliveryAttempt :one
UPDATE deliveries
SET attempts = attempts + 1,
    last_attempt_at = datetime('now'),
    error_message = ?
WHERE id = ? AND status = 'pending'
RETURNING seq, id, webhook_id, destination_id, status, attempts, last_attempt_at, delivered_at, error_message, notification_sent, created_at
`

type RecordDeliveryAttemptParams struct {
	ErrorMessage sql.NullString `json:"error_message"`
	ID           string         `json:"id"`
}

// Transient failure (5xx or network error) - stays pending for retry after backoff.
func (q *Queries) RecordDeliveryAttempt(ctx context.Context, arg RecordDeliveryAttemptParams) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, recordDeliveryAttempt, arg.ErrorMessage, arg.ID)
	var i Delivery
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.WebhookID,
		&i.DestinationID,
		&i.Status,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.DeliveredAt,
		&i.ErrorMessage,
		&i.NotificationSent,
		&i.CreatedAt,
	)
	return i, err
}

const resetDeliveryForReplay = `-- name: ResetDeliveryForReplay :one
UPDATE deliveries
SET status = 'pending',
    attempts = 0,
    last_attempt_at = NULL,
    delivered_at = NULL,
    error_message = NULL,
    notification_sent = 0
WHERE id = ?
RETURNING seq, id, webhook_id, destination_id, status, attempts, last_attempt_at, delivered_at, error_message, notification_sent, created_at
`

func (q *Queries) ResetDeliveryForReplay(ctx context.Context, id string) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, resetDeliveryForReplay, id)
	var i Delivery
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.WebhookID,
		&i.DestinationID,
		&i.Status,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.DeliveredAt,
		&i.ErrorMessage,
		&i.NotificationSent,
		&i.CreatedAt,
	)
	return i, err
}
