// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: destinations.sql

package db

import (
	"context"
	"database/sql"
)

const countDestinationsByEndpoint = `-- name: CountDestinationsByEndpoint :one
SELECT COUNT(*) FROM destinations WHERE endpoint_id = ?
`

func (q *Queries) CountDestinationsByEndpoint(ctx context.Context, endpointID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDestinationsByEndpoint, endpointID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnabledDestinationsByEndpoint = `-- name: CountEnabledDestinationsByEndpoint :one
SELECT COUNT(*) FROM destinations WHERE endpoint_id = ? AND enabled = 1
`

func (q *Queries) CountEnabledDestinationsByEndpoint(ctx context.Context, endpointID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnabledDestinationsByEndpoint, endpointID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDestination = `-- name: CreateDestination :one
INSERT INTO destinations (id, endpoint_id, name, url, enabled, position, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))
RETURNING id, endpoint_id, name, url, enabled, position, created_at, updated_at
`

type CreateDestinationParams struct {
	ID         string `json:"id"`
	EndpointID string `json:"endpoint_id"`
	Name       string `json:"name"`
	Url        string `json:"url"`
	Enabled    int64  `json:"enabled"`
	Position   int64  `json:"position"`
}

func (q *Queries) CreateDestination(ctx context.Context, arg CreateDestinationParams) (Destination, error) {
	row := q.db.QueryRowContext(ctx, createDestination,
		arg.ID,
		arg.EndpointID,
		arg.Name,
		arg.Url,
		arg.Enabled,
		arg.Position,
	)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.Name,
		&i.Url,
		&i.Enabled,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDestination = `-- name: DeleteDestination :exec
DELETE FROM destinations WHERE id = ?
`

// Deliveries for the destination are removed by ON DELETE CASCADE.
func (q *Queries) DeleteDestination(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDestination, id)
	return err
}

const getDestination = `-- name: GetDestination :one
SELECT id, endpoint_id, name, url, enabled, position, created_at, updated_at FROM destinations WHERE id = ?
`

// System query: no user filter
func (q *Queries) GetDestination(ctx context.Context, id string) (Destination, error) {
	row := q.db.QueryRowContext(ctx, getDestination, id)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.Name,
		&i.Url,
		&i.Enabled,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDestinationForUser = `-- name: GetDestinationForUser :one
SELECT d.id, d.endpoint_id, d.name, d.url, d.enabled, d.position, d.created_at, d.updated_at FROM destinations d
JOIN endpoints e ON d.endpoint_id = e.id
WHERE d.id = ? AND e.user_id = ?
`

type GetDestinationForUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

// User-facing query: validates endpoint ownership via JOIN
func (q *Queries) GetDestinationForUser(ctx context.Context, arg GetDestinationForUserParams) (Destination, error) {
	row := q.db.QueryRowContext(ctx, getDestinationForUser, arg.ID, arg.UserID)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.Name,
		&i.Url,
		&i.Enabled,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDestinationsByEndpoint = `-- name: ListDestinationsByEndpoint :many
SELECT id, endpoint_id, name, url, enabled, position, created_at, updated_at FROM destinations
WHERE endpoint_id = ?
ORDER BY position ASC, created_at ASC, id ASC
`

// Ordered so that the first row is the endpoint's primary destination.
func (q *Queries) ListDestinationsByEndpoint(ctx context.Context, endpointID string) ([]Destination, error) {
	rows, err := q.db.QueryContext(ctx, listDestinationsByEndpoint, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Destination{}
	for rows.Next() {
		var i Destination
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.Name,
			&i.Url,
			&i.Enabled,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledDestinationsByEndpoint = `-- name: ListEnabledDestinationsByEndpoint :many
SELECT id, endpoint_id, name, url, enabled, position, created_at, updated_at FROM destinations
WHERE endpoint_id = ? AND enabled = 1
ORDER BY position ASC, created_at ASC, id ASC
`

func (q *Queries) ListEnabledDestinationsByEndpoint(ctx context.Context, endpointID string) ([]Destination, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledDestinationsByEndpoint, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Destination{}
	for rows.Next() {
		var i Destination
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.Name,
			&i.Url,
			&i.Enabled,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDestinationPosition = `-- name: NextDestinationPosition :one
SELECT CAST(COALESCE(MAX(position), -1) + 1 AS INTEGER) FROM destinations WHERE endpoint_id = ?
`

func (q *Queries) NextDestinationPosition(ctx context.Context, endpointID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextDestinationPosition, endpointID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateDestination = `-- name: UpdateDestination :one
UPDATE destinations
SET name = COALESCE(?1, name),
    url = COALESCE(?2, url),
    enabled = COALESCE(?3, enabled),
    updated_at = datetime('now')
WHERE id = ?4
RETURNING id, endpoint_id, name, url, enabled, position, created_at, updated_at
`

type UpdateDestinationParams struct {
	Name    sql.NullString `json:"name"`
	Url     sql.NullString `json:"url"`
	Enabled sql.NullInt64  `json:"enabled"`
	ID      string         `json:"id"`
}

func (q *Queries) UpdateDestination(ctx context.Context, arg UpdateDestinationParams) (Destination, error) {
	row := q.db.QueryRowContext(ctx, updateDestination,
		arg.Name,
		arg.Url,
		arg.Enabled,
		arg.ID,
	)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.Name,
		&i.Url,
		&i.Enabled,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
