// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: endpoints.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const countEndpoints = `-- name: CountEndpoints :one
SELECT COUNT(*) FROM endpoints WHERE user_id = ?
`

func (q *Queries) CountEndpoints(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEndpoints, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO endpoints (id, user_id, name, provider_type, signature_secret_encrypted, verification_config_encrypted, destination_url, muted, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, 0, datetime('now'), datetime('now'))
RETURNING id, user_id, name, provider_type, signature_secret_encrypted, verification_config_encrypted, destination_url, muted, created_at, updated_at
`

type CreateEndpointParams struct {
	ID                          string `json:"id"`
	UserID                      string `json:"user_id"`
	Name                        string `json:"name"`
	ProviderType                string `json:"provider_type"`
	SignatureSecretEncrypted    []byte `json:"signature_secret_encrypted"`
	VerificationConfigEncrypted []byte `json:"verification_config_encrypted"`
	DestinationUrl              string `json:"destination_url"`
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRowContext(ctx, createEndpoint,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.ProviderType,
		arg.SignatureSecretEncrypted,
		arg.VerificationConfigEncrypted,
		arg.DestinationUrl,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ProviderType,
		&i.SignatureSecretEncrypted,
		&i.VerificationConfigEncrypted,
		&i.DestinationUrl,
		&i.Muted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEndpoint = `-- name: DeleteEndpoint :exec
DELETE FROM endpoints WHERE id = ? AND user_id = ?
`

type DeleteEndpointParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteEndpoint(ctx context.Context, arg DeleteEndpointParams) error {
	_, err := q.db.ExecContext(ctx, deleteEndpoint, arg.ID, arg.UserID)
	return err
}

const getEndpoint = `-- name: GetEndpoint :one
SELECT id, user_id, name, provider_type, signature_secret_encrypted, verification_config_encrypted, destination_url, muted, created_at, updated_at FROM endpoints WHERE id = ? AND user_id = ?
`

type GetEndpointParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetEndpoint(ctx context.Context, arg GetEndpointParams) (Endpoint, error) {
	row := q.db.QueryRowContext(ctx, getEndpoint, arg.ID, arg.UserID)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ProviderType,
		&i.SignatureSecretEncrypted,
		&i.VerificationConfigEncrypted,
		&i.DestinationUrl,
		&i.Muted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndpointByID = `-- name: GetEndpointByID :one
SELECT id, user_id, name, provider_type, signature_secret_encrypted, verification_config_encrypted, destination_url, muted
FROM endpoints
WHERE id = ?
`

type GetEndpointByIDRow struct {
	ID                          string `json:"id"`
	UserID                      string `json:"user_id"`
	Name                        string `json:"name"`
	ProviderType                string `json:"provider_type"`
	SignatureSecretEncrypted    []byte `json:"signature_secret_encrypted"`
	VerificationConfigEncrypted []byte `json:"verification_config_encrypted"`
	DestinationUrl              string `json:"destination_url"`
	Muted                       int64  `json:"muted"`
}

// Public query for webhook ingestion and relay auth - no user_id filter
func (q *Queries) GetEndpointByID(ctx context.Context, id string) (GetEndpointByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEndpointByID, id)
	var i GetEndpointByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ProviderType,
		&i.SignatureSecretEncrypted,
		&i.VerificationConfigEncrypted,
		&i.DestinationUrl,
		&i.Muted,
	)
	return i, err
}

const getEndpointsByIDs = `-- name: GetEndpointsByIDs :many
SELECT id, name FROM endpoints WHERE user_id = ? AND id IN (/*SLICE:ids*/?)
`

type GetEndpointsByIDsParams struct {
	UserID string   `json:"user_id"`
	Ids    []string `json:"ids"`
}

type GetEndpointsByIDsRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// Get endpoints by list of IDs for a specific user
func (q *Queries) GetEndpointsByIDs(ctx context.Context, arg GetEndpointsByIDsParams) ([]GetEndpointsByIDsRow, error) {
	query := getEndpointsByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEndpointsByIDsRow{}
	for rows.Next() {
		var i GetEndpointsByIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpoints = `-- name: ListEndpoints :many
SELECT id, user_id, name, provider_type, signature_secret_encrypted, verification_config_encrypted, destination_url, muted, created_at, updated_at FROM endpoints WHERE user_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListEndpointsParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListEndpoints(ctx context.Context, arg ListEndpointsParams) ([]Endpoint, error) {
	rows, err := q.db.QueryContext(ctx, listEndpoints, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ProviderType,
			&i.SignatureSecretEncrypted,
			&i.VerificationConfigEncrypted,
			&i.DestinationUrl,
			&i.Muted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEndpoint = `-- name: UpdateEndpoint :one
UPDATE endpoints
SET name = COALESCE(?3, name),
    signature_secret_encrypted = COALESCE(?4, signature_secret_encrypted),
    verification_config_encrypted = COALESCE(?5, verification_config_encrypted),
    destination_url = COALESCE(?6, destination_url),
    muted = COALESCE(?7, muted),
    updated_at = datetime('now')
WHERE id = ? AND user_id = ?
RETURNING id, user_id, name, provider_type, signature_secret_encrypted, verification_config_encrypted, destination_url, muted, created_at, updated_at
`

type UpdateEndpointParams struct {
	Name                        sql.NullString `json:"name"`
	SignatureSecretEncrypted    []byte         `json:"signature_secret_encrypted"`
	VerificationConfigEncrypted []byte         `json:"verification_config_encrypted"`
	DestinationUrl              sql.NullString `json:"destination_url"`
	Muted                       sql.NullInt64  `json:"muted"`
	ID                          string         `json:"id"`
	UserID                      string         `json:"user_id"`
}

func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRowContext(ctx, updateEndpoint,
		arg.Name,
		arg.SignatureSecretEncrypted,
		arg.VerificationConfigEncrypted,
		arg.DestinationUrl,
		arg.Muted,
		arg.ID,
		arg.UserID,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ProviderType,
		&i.SignatureSecretEncrypted,
		&i.VerificationConfigEncrypted,
		&i.DestinationUrl,
		&i.Muted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
