// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: endpoints.sql

package db

import (
	"context"
	"database/sql"
)

const countEndpoints = `-- name: CountEndpoints :one
SELECT COUNT(*) FROM endpoints
`

func (q *Queries) CountEndpoints(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEndpoints)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO endpoints (id, name, provider_type, signature_secret_encrypted, destination_url, muted, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 0, datetime('now'), datetime('now'))
RETURNING id, name, provider_type, signature_secret_encrypted, destination_url, muted, created_at, updated_at
`

type CreateEndpointParams struct {
	ID                       string `json:"id"`
	Name                     string `json:"name"`
	ProviderType             string `json:"provider_type"`
	SignatureSecretEncrypted []byte `json:"signature_secret_encrypted"`
	DestinationUrl           string `json:"destination_url"`
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRowContext(ctx, createEndpoint,
		arg.ID,
		arg.Name,
		arg.ProviderType,
		arg.SignatureSecretEncrypted,
		arg.DestinationUrl,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.SignatureSecretEncrypted,
		&i.DestinationUrl,
		&i.Muted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEndpoint = `-- name: DeleteEndpoint :exec
DELETE FROM endpoints WHERE id = ?
`

func (q *Queries) DeleteEndpoint(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEndpoint, id)
	return err
}

const getEndpoint = `-- name: GetEndpoint :one
SELECT id, name, provider_type, signature_secret_encrypted, destination_url, muted, created_at, updated_at FROM endpoints WHERE id = ?
`

func (q *Queries) GetEndpoint(ctx context.Context, id string) (Endpoint, error) {
	row := q.db.QueryRowContext(ctx, getEndpoint, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.SignatureSecretEncrypted,
		&i.DestinationUrl,
		&i.Muted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndpointByID = `-- name: GetEndpointByID :one
SELECT id, name, provider_type, signature_secret_encrypted, destination_url, muted
FROM endpoints
WHERE id = ?
`

type GetEndpointByIDRow struct {
	ID                       string `json:"id"`
	Name                     string `json:"name"`
	ProviderType             string `json:"provider_type"`
	SignatureSecretEncrypted []byte `json:"signature_secret_encrypted"`
	DestinationUrl           string `json:"destination_url"`
	Muted                    int64  `json:"muted"`
}

func (q *Queries) GetEndpointByID(ctx context.Context, id string) (GetEndpointByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEndpointByID, id)
	var i GetEndpointByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.SignatureSecretEncrypted,
		&i.DestinationUrl,
		&i.Muted,
	)
	return i, err
}

const listEndpoints = `-- name: ListEndpoints :many
SELECT id, name, provider_type, signature_secret_encrypted, destination_url, muted, created_at, updated_at FROM endpoints ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListEndpointsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListEndpoints(ctx context.Context, arg ListEndpointsParams) ([]Endpoint, error) {
	rows, err := q.db.QueryContext(ctx, listEndpoints, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProviderType,
			&i.SignatureSecretEncrypted,
			&i.DestinationUrl,
			&i.Muted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEndpoint = `-- name: UpdateEndpoint :one
UPDATE endpoints
SET name = COALESCE(?2, name),
    signature_secret_encrypted = COALESCE(?3, signature_secret_encrypted),
    destination_url = COALESCE(?4, destination_url),
    muted = COALESCE(?5, muted),
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, name, provider_type, signature_secret_encrypted, destination_url, muted, created_at, updated_at
`

type UpdateEndpointParams struct {
	Name                     sql.NullString `json:"name"`
	SignatureSecretEncrypted []byte         `json:"signature_secret_encrypted"`
	DestinationUrl           sql.NullString `json:"destination_url"`
	Muted                    sql.NullInt64  `json:"muted"`
	ID                       string         `json:"id"`
}

func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRowContext(ctx, updateEndpoint,
		arg.Name,
		arg.SignatureSecretEncrypted,
		arg.DestinationUrl,
		arg.Muted,
		arg.ID,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.SignatureSecretEncrypted,
		&i.DestinationUrl,
		&i.Muted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
