// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type ApiToken struct {
	ID         string         `json:"id"`
	UserID     string         `json:"user_id"`
	Username   string         `json:"username"`
	TokenHash  string         `json:"token_hash"`
	Name       string         `json:"name"`
	CreatedAt  string         `json:"created_at"`
	LastUsedAt sql.NullString `json:"last_used_at"`
	Revoked    int64          `json:"revoked"`
}

type Endpoint struct {
	ID                          string `json:"id"`
	UserID                      string `json:"user_id"`
	Name                        string `json:"name"`
	ProviderType                string `json:"provider_type"`
	SignatureSecretEncrypted    []byte `json:"signature_secret_encrypted"`
	VerificationConfigEncrypted []byte `json:"verification_config_encrypted"`
	DestinationUrl              string `json:"destination_url"`
	Muted                       int64  `json:"muted"`
	CreatedAt                   string `json:"created_at"`
	UpdatedAt                   string `json:"updated_at"`
}

type Session struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	Username  string         `json:"username"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	CreatedAt string         `json:"created_at"`
	ExpiresAt string         `json:"expires_at"`
}

type UserSetting struct {
	UserID                    string         `json:"user_id"`
	Username                  string         `json:"username"`
	GithubName                sql.NullString `json:"github_name"`
	GithubEmail               sql.NullString `json:"github_email"`
	GithubProfileUrl          sql.NullString `json:"github_profile_url"`
	AvatarUrl                 sql.NullString `json:"avatar_url"`
	TelegramBotTokenEncrypted []byte         `json:"telegram_bot_token_encrypted"`
	TelegramChatID            sql.NullString `json:"telegram_chat_id"`
	TelegramEnabled           int64          `json:"telegram_enabled"`
	ThemePreference           string         `json:"theme_preference"`
	CreatedAt                 string         `json:"created_at"`
	UpdatedAt                 string         `json:"updated_at"`
	LastLoginAt               string         `json:"last_login_at"`
}

type Webhook struct {
	ID               string         `json:"id"`
	EndpointID       string         `json:"endpoint_id"`
	ReceivedAt       string         `json:"received_at"`
	Headers          string         `json:"headers"`
	Payload          []byte         `json:"payload"`
	SignatureValid   int64          `json:"signature_valid"`
	Status           string         `json:"status"`
	Attempts         int64          `json:"attempts"`
	LastAttemptAt    sql.NullString `json:"last_attempt_at"`
	DeliveredAt      sql.NullString `json:"delivered_at"`
	ErrorMessage     sql.NullString `json:"error_message"`
	NotificationSent int64          `json:"notification_sent"`
}
