// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Endpoint struct {
	ID                       string `json:"id"`
	Name                     string `json:"name"`
	ProviderType             string `json:"provider_type"`
	SignatureSecretEncrypted []byte `json:"signature_secret_encrypted"`
	DestinationUrl           string `json:"destination_url"`
	Muted                    int64  `json:"muted"`
	CreatedAt                string `json:"created_at"`
	UpdatedAt                string `json:"updated_at"`
}

type Session struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	Username  string         `json:"username"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	CreatedAt string         `json:"created_at"`
	ExpiresAt string         `json:"expires_at"`
}

type Webhook struct {
	ID               string         `json:"id"`
	EndpointID       string         `json:"endpoint_id"`
	ReceivedAt       string         `json:"received_at"`
	Headers          string         `json:"headers"`
	Payload          []byte         `json:"payload"`
	SignatureValid   int64          `json:"signature_valid"`
	Status           string         `json:"status"`
	Attempts         int64          `json:"attempts"`
	LastAttemptAt    sql.NullString `json:"last_attempt_at"`
	DeliveredAt      sql.NullString `json:"delivered_at"`
	ErrorMessage     sql.NullString `json:"error_message"`
	NotificationSent int64          `json:"notification_sent"`
}
