// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tokens.sql

package db

import (
	"context"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (id, user_id, username, token_hash, name)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, username, token_hash, name, created_at, last_used_at, revoked
`

type CreateAPITokenParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Username  string `json:"username"`
	TokenHash string `json:"token_hash"`
	Name      string `json:"name"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, createAPIToken,
		arg.ID,
		arg.UserID,
		arg.Username,
		arg.TokenHash,
		arg.Name,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.TokenHash,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Revoked,
	)
	return i, err
}

const deleteRevokedAPITokens = `-- name: DeleteRevokedAPITokens :execrows
DELETE FROM api_tokens
WHERE revoked = 1
  AND (last_used_at IS NULL OR last_used_at < datetime('now', '-30 days'))
`

func (q *Queries) DeleteRevokedAPITokens(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRevokedAPITokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, username, token_hash, name, created_at, last_used_at, revoked FROM api_tokens
WHERE token_hash = ?
  AND revoked = 0
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.TokenHash,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Revoked,
	)
	return i, err
}

const getAPITokensByUser = `-- name: GetAPITokensByUser :many
SELECT id, user_id, username, token_hash, name, created_at, last_used_at, revoked FROM api_tokens
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetAPITokensByUser(ctx context.Context, userID string) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, getAPITokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.TokenHash,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :exec
UPDATE api_tokens
SET revoked = 1
WHERE id = ?
`

func (q *Queries) RevokeAPIToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeAPIToken, id)
	return err
}

const revokeAllUserAPITokens = `-- name: RevokeAllUserAPITokens :exec
UPDATE api_tokens
SET revoked = 1
WHERE user_id = ?
`

func (q *Queries) RevokeAllUserAPITokens(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserAPITokens, userID)
	return err
}

const updateAPITokenLastUsed = `-- name: UpdateAPITokenLastUsed :exec
UPDATE api_tokens
SET last_used_at = datetime('now')
WHERE id = ?
`

func (q *Queries) UpdateAPITokenLastUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateAPITokenLastUsed, id)
	return err
}
