// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user_settings.sql

package db

import (
	"context"
	"database/sql"
)

const countAllEndpoints = `-- name: CountAllEndpoints :one
SELECT COUNT(*) FROM endpoints
`

func (q *Queries) CountAllEndpoints(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllEndpoints)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM user_settings
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEndpointOwnerTelegramConfig = `-- name: GetEndpointOwnerTelegramConfig :one
SELECT
    us.user_id,
    us.telegram_bot_token_encrypted,
    us.telegram_chat_id,
    us.telegram_enabled
FROM endpoints e
JOIN user_settings us ON e.user_id = us.user_id
WHERE e.id = ?
`

type GetEndpointOwnerTelegramConfigRow struct {
	UserID                    string         `json:"user_id"`
	TelegramBotTokenEncrypted []byte         `json:"telegram_bot_token_encrypted"`
	TelegramChatID            sql.NullString `json:"telegram_chat_id"`
	TelegramEnabled           int64          `json:"telegram_enabled"`
}

// Get the endpoint owner's Telegram configuration for sending notifications
func (q *Queries) GetEndpointOwnerTelegramConfig(ctx context.Context, id string) (GetEndpointOwnerTelegramConfigRow, error) {
	row := q.db.QueryRowContext(ctx, getEndpointOwnerTelegramConfig, id)
	var i GetEndpointOwnerTelegramConfigRow
	err := row.Scan(
		&i.UserID,
		&i.TelegramBotTokenEncrypted,
		&i.TelegramChatID,
		&i.TelegramEnabled,
	)
	return i, err
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT user_id, username, github_name, github_email, github_profile_url, avatar_url, telegram_bot_token_encrypted, telegram_chat_id, telegram_enabled, theme_preference, created_at, updated_at, last_login_at FROM user_settings WHERE user_id = ?
`

func (q *Queries) GetUserSettings(ctx context.Context, userID string) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, getUserSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.GithubName,
		&i.GithubEmail,
		&i.GithubProfileUrl,
		&i.AvatarUrl,
		&i.TelegramBotTokenEncrypted,
		&i.TelegramChatID,
		&i.TelegramEnabled,
		&i.ThemePreference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserSettingsByUsername = `-- name: GetUserSettingsByUsername :one
SELECT user_id, username, github_name, github_email, github_profile_url, avatar_url, telegram_bot_token_encrypted, telegram_chat_id, telegram_enabled, theme_preference, created_at, updated_at, last_login_at FROM user_settings WHERE username = ?
`

func (q *Queries) GetUserSettingsByUsername(ctx context.Context, username string) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, getUserSettingsByUsername, username)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.GithubName,
		&i.GithubEmail,
		&i.GithubProfileUrl,
		&i.AvatarUrl,
		&i.TelegramBotTokenEncrypted,
		&i.TelegramChatID,
		&i.TelegramEnabled,
		&i.ThemePreference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const updateUserTelegramSettings = `-- name: UpdateUserTelegramSettings :one
UPDATE user_settings
SET telegram_bot_token_encrypted = ?,
    telegram_chat_id = ?,
    telegram_enabled = ?,
    updated_at = datetime('now')
WHERE user_id = ?
RETURNING user_id, username, github_name, github_email, github_profile_url, avatar_url, telegram_bot_token_encrypted, telegram_chat_id, telegram_enabled, theme_preference, created_at, updated_at, last_login_at
`

type UpdateUserTelegramSettingsParams struct {
	TelegramBotTokenEncrypted []byte         `json:"telegram_bot_token_encrypted"`
	TelegramChatID            sql.NullString `json:"telegram_chat_id"`
	TelegramEnabled           int64          `json:"telegram_enabled"`
	UserID                    string         `json:"user_id"`
}

func (q *Queries) UpdateUserTelegramSettings(ctx context.Context, arg UpdateUserTelegramSettingsParams) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, updateUserTelegramSettings,
		arg.TelegramBotTokenEncrypted,
		arg.TelegramChatID,
		arg.TelegramEnabled,
		arg.UserID,
	)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.GithubName,
		&i.GithubEmail,
		&i.GithubProfileUrl,
		&i.AvatarUrl,
		&i.TelegramBotTokenEncrypted,
		&i.TelegramChatID,
		&i.TelegramEnabled,
		&i.ThemePreference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const updateUserTheme = `-- name: UpdateUserTheme :one
UPDATE user_settings
SET theme_preference = ?,
    updated_at = datetime('now')
WHERE user_id = ?
RETURNING user_id, username, github_name, github_email, github_profile_url, avatar_url, telegram_bot_token_encrypted, telegram_chat_id, telegram_enabled, theme_preference, created_at, updated_at, last_login_at
`

type UpdateUserThemeParams struct {
	ThemePreference string `json:"theme_preference"`
	UserID          string `json:"user_id"`
}

func (q *Queries) UpdateUserTheme(ctx context.Context, arg UpdateUserThemeParams) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, updateUserTheme, arg.ThemePreference, arg.UserID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.GithubName,
		&i.GithubEmail,
		&i.GithubProfileUrl,
		&i.AvatarUrl,
		&i.TelegramBotTokenEncrypted,
		&i.TelegramChatID,
		&i.TelegramEnabled,
		&i.ThemePreference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const upsertUserSettings = `-- name: UpsertUserSettings :one
INSERT INTO user_settings (
    user_id,
    username,
    github_name,
    github_email,
    github_profile_url,
    avatar_url,
    last_login_at
)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT(user_id) DO UPDATE SET
    username = excluded.username,
    github_name = excluded.github_name,
    github_email = excluded.github_email,
    github_profile_url = excluded.github_profile_url,
    avatar_url = excluded.avatar_url,
    last_login_at = datetime('now'),
    updated_at = datetime('now')
RETURNING user_id, username, github_name, github_email, github_profile_url, avatar_url, telegram_bot_token_encrypted, telegram_chat_id, telegram_enabled, theme_preference, created_at, updated_at, last_login_at
`

type UpsertUserSettingsParams struct {
	UserID           string         `json:"user_id"`
	Username         string         `json:"username"`
	GithubName       sql.NullString `json:"github_name"`
	GithubEmail      sql.NullString `json:"github_email"`
	GithubProfileUrl sql.NullString `json:"github_profile_url"`
	AvatarUrl        sql.NullString `json:"avatar_url"`
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertUserSettings,
		arg.UserID,
		arg.Username,
		arg.GithubName,
		arg.GithubEmail,
		arg.GithubProfileUrl,
		arg.AvatarUrl,
	)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.GithubName,
		&i.GithubEmail,
		&i.GithubProfileUrl,
		&i.AvatarUrl,
		&i.TelegramBotTokenEncrypted,
		&i.TelegramChatID,
		&i.TelegramEnabled,
		&i.ThemePreference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
