// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: webhooks.sql

package db

import (
	"context"
	"database/sql"
)

const countWebhooks = `-- name: CountWebhooks :one
SELECT COUNT(*) FROM webhooks w
JOIN endpoints e ON w.endpoint_id = e.id
WHERE e.user_id = ?1
  AND (?2 IS NULL OR w.endpoint_id = ?2)
  AND (?3 IS NULL OR w.status = ?3)
`

type CountWebhooksParams struct {
	UserID     string      `json:"user_id"`
	EndpointID interface{} `json:"endpoint_id"`
	Status     interface{} `json:"status"`
}

// User-facing query: counts webhooks owned by user
func (q *Queries) CountWebhooks(ctx context.Context, arg CountWebhooksParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWebhooks, arg.UserID, arg.EndpointID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (id, endpoint_id, received_at, headers, payload, signature_valid, status, attempts)
VALUES (?, ?, datetime('now'), ?, ?, ?, 'pending', 0)
RETURNING id, endpoint_id, received_at, headers, payload, signature_valid, status, attempts, last_attempt_at, delivered_at, error_message, notification_sent
`

type CreateWebhookParams struct {
	ID             string `json:"id"`
	EndpointID     string `json:"endpoint_id"`
	Headers        string `json:"headers"`
	Payload        []byte `json:"payload"`
	SignatureValid int64  `json:"signature_valid"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, createWebhook,
		arg.ID,
		arg.EndpointID,
		arg.Headers,
		arg.Payload,
		arg.SignatureValid,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.ReceivedAt,
		&i.Headers,
		&i.Payload,
		&i.SignatureValid,
		&i.Status,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.DeliveredAt,
		&i.ErrorMessage,
		&i.NotificationSent,
	)
	return i, err
}

const deleteDeadLetterWebhooks = `-- name: DeleteDeadLetterWebhooks :execrows
DELETE FROM webhooks
WHERE status = 'dead_letter'
  AND received_at < datetime('now', '-14 days')
`

// System query: cleanup old dead letter webhooks (no user filter)
func (q *Queries) DeleteDeadLetterWebhooks(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDeadLetterWebhooks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDeliveredWebhooks = `-- name: DeleteDeliveredWebhooks :execrows
DELETE FROM webhooks
WHERE status = 'delivered'
  AND delivered_at < datetime('now', '-7 days')
`

// System query: cleanup old delivered webhooks (no user filter)
func (q *Queries) DeleteDeliveredWebhooks(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDeliveredWebhooks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteFailedWebhooks = `-- name: DeleteFailedWebhooks :execrows
DELETE FROM webhooks
WHERE status = 'failed'
  AND last_attempt_at < datetime('now', '-7 days')
`

// System query: cleanup old failed webhooks (no user filter)
func (q *Queries) DeleteFailedWebhooks(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFailedWebhooks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getQueueStats = `-- name: GetQueueStats :one
SELECT
    SUM(CASE WHEN w.status = 'pending' THEN 1 ELSE 0 END) AS pending_count,
    SUM(CASE WHEN w.status = 'failed' THEN 1 ELSE 0 END) AS failed_count,
    SUM(CASE WHEN w.status = 'dead_letter' THEN 1 ELSE 0 END) AS dead_letter_count
FROM webhooks w
JOIN endpoints e ON w.endpoint_id = e.id
WHERE e.user_id = ?
`

type GetQueueStatsRow struct {
	PendingCount    sql.NullFloat64 `json:"pending_count"`
	FailedCount     sql.NullFloat64 `json:"failed_count"`
	DeadLetterCount sql.NullFloat64 `json:"dead_letter_count"`
}

// User-facing query: gets queue stats for user's endpoints
func (q *Queries) GetQueueStats(ctx context.Context, userID string) (GetQueueStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getQueueStats, userID)
	var i GetQueueStatsRow
	err := row.Scan(&i.PendingCount, &i.FailedCount, &i.DeadLetterCount)
	return i, err
}

const getWebhook = `-- name: GetWebhook :one
SELECT w.id, w.endpoint_id, w.received_at, w.headers, w.payload, w.signature_valid, w.status, w.attempts, w.last_attempt_at, w.delivered_at, w.error_message, w.notification_sent FROM webhooks w
JOIN endpoints e ON w.endpoint_id = e.id
WHERE w.id = ? AND e.user_id = ?
`

type GetWebhookParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

// User-facing query: validates endpoint ownership via JOIN
func (q *Queries) GetWebhook(ctx context.Context, arg GetWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhook, arg.ID, arg.UserID)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.ReceivedAt,
		&i.Headers,
		&i.Payload,
		&i.SignatureValid,
		&i.Status,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.DeliveredAt,
		&i.ErrorMessage,
		&i.NotificationSent,
	)
	return i, err
}

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, endpoint_id, received_at, headers, payload, signature_valid, status, attempts, last_attempt_at, delivered_at, error_message, notification_sent FROM webhooks WHERE id = ?
`

// System query: no user filter (used when re-deriving a webhook's status)
func (q *Queries) GetWebhookByID(ctx context.Context, id string) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhookByID, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.ReceivedAt,
		&i.Headers,
		&i.Payload,
		&i.SignatureValid,
		&i.Status,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.DeliveredAt,
		&i.ErrorMessage,
		&i.NotificationSent,
	)
	return i, err
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT w.id, w.endpoint_id, w.received_at, w.headers, w.payload, w.signature_valid, w.status, w.attempts, w.last_attempt_at, w.delivered_at, w.error_message, w.notification_sent FROM webhooks w
JOIN endpoints e ON w.endpoint_id = e.id
WHERE e.user_id = ?1
  AND (?2 IS NULL OR w.endpoint_id = ?2)
  AND (?3 IS NULL OR w.status = ?3)
ORDER BY w.received_at DESC
LIMIT ?5 OFFSET ?4
`

type ListWebhooksParams struct {
	UserID     string      `json:"user_id"`
	EndpointID interface{} `json:"endpoint_id"`
	Status     interface{} `json:"status"`
	Offset     int64       `json:"offset"`
	Limit      int64       `json:"limit"`
}

// User-facing query: filters by endpoint ownership
func (q *Queries) ListWebhooks(ctx context.Context, arg ListWebhooksParams) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooks,
		arg.UserID,
		arg.EndpointID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.ReceivedAt,
			&i.Headers,
			&i.Payload,
			&i.SignatureValid,
			&i.Status,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.DeliveredAt,
			&i.ErrorMessage,
			&i.NotificationSent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhookRollup = `-- name: UpdateWebhookRollup :exec
UPDATE webhooks
SET status = ?,
    attempts = ?,
    last_attempt_at = ?,
    delivered_at = ?,
    error_message = ?
WHERE id = ?
`

type UpdateWebhookRollupParams struct {
	Status        string         `json:"status"`
	Attempts      int64          `json:"attempts"`
	LastAttemptAt sql.NullString `json:"last_attempt_at"`
	DeliveredAt   sql.NullString `json:"delivered_at"`
	ErrorMessage  sql.NullString `json:"error_message"`
	ID            string         `json:"id"`
}

// System query: store the status derived from the webhook's deliveries (see db.Rollup).
func (q *Queries) UpdateWebhookRollup(ctx context.Context, arg UpdateWebhookRollupParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhookRollup,
		arg.Status,
		arg.Attempts,
		arg.LastAttemptAt,
		arg.DeliveredAt,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}
