// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file hookly/v1/relay.proto (package hookly.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file hookly/v1/relay.proto.
 */
export const file_hookly_v1_relay: GenFile = /*@__PURE__*/
  fileDesc("ChVob29rbHkvdjEvcmVsYXkucHJvdG8SCWhvb2tseS52MSKaAQoNU3RyZWFtUmVxdWVzdBIsCgdjb25uZWN0GAEgASgLMhkuaG9va2x5LnYxLkNvbm5lY3RSZXF1ZXN0SAASJQoDYWNrGAIgASgLMhYuaG9va2x5LnYxLkRlbGl2ZXJ5QWNrSAASKQoJaGVhcnRiZWF0GAMgASgLMhQuaG9va2x5LnYxLkhlYXJ0YmVhdEgAQgkKB21lc3NhZ2UirQEKDlN0cmVhbVJlc3BvbnNlEjYKEGNvbm5lY3RfcmVzcG9uc2UYASABKAsyGi5ob29rbHkudjEuQ29ubmVjdFJlc3BvbnNlSAASLQoHd2ViaG9vaxgCIAEoCzIaLmhvb2tseS52MS5XZWJob29rRW52ZWxvcGVIABIpCgloZWFydGJlYXQYAyABKAsyFC5ob29rbHkudjEuSGVhcnRiZWF0SABCCQoHbWVzc2FnZSJFCg5Db25uZWN0UmVxdWVzdBIOCgZodWJfaWQYASABKAkSDQoFdG9rZW4YAiABKAkSFAoMZW5kcG9pbnRfaWRzGAMgAygJIjEKD0Nvbm5lY3RSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIEg0KBWVycm9yGAIgASgJIh4KCUhlYXJ0YmVhdBIRCgl0aW1lc3RhbXAYASABKAMiiAIKD1dlYmhvb2tFbnZlbG9wZRIKCgJpZBgBIAEoCRITCgtlbmRwb2ludF9pZBgCIAEoCRIXCg9kZXN0aW5hdGlvbl91cmwYAyABKAkSLwoLcmVjZWl2ZWRfYXQYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjgKB2hlYWRlcnMYBSADKAsyJy5ob29rbHkudjEuV2ViaG9va0VudmVsb3BlLkhlYWRlcnNFbnRyeRIPCgdwYXlsb2FkGAYgASgMEg8KB2F0dGVtcHQYByABKAUaLgoMSGVhZGVyc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEieQoLRGVsaXZlcnlBY2sSEgoKd2ViaG9va19pZBgBIAEoCRIPCgdzdWNjZXNzGAIgASgIEhMKC3N0YXR1c19jb2RlGAMgASgFEhUKDWVycm9yX21lc3NhZ2UYBCABKAkSGQoRcGVybWFuZW50X2ZhaWx1cmUYBSABKAgyUQoMUmVsYXlTZXJ2aWNlEkEKBlN0cmVhbRIYLmhvb2tseS52MS5TdHJlYW1SZXF1ZXN0GhkuaG9va2x5LnYxLlN0cmVhbVJlc3BvbnNlKAEwAUKRAQoNY29tLmhvb2tseS52MUIKUmVsYXlQcm90b1ABWi9ob29rcy5keDMxNC5jb20vaW50ZXJuYWwvYXBpL2hvb2tseS92MTtob29rbHl2MaICA0hYWKoCCUhvb2tseS5WMcoCCUhvb2tseVxWMeICFUhvb2tseVxWMVxHUEJNZXRhZGF0YeoCCkhvb2tseTo6VjFiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * Messages from home-hub to edge
 *
 * @generated from message hookly.v1.StreamRequest
 */
export type StreamRequest = Message<"hookly.v1.StreamRequest"> & {
  /**
   * @generated from oneof hookly.v1.StreamRequest.message
   */
  message: {
    /**
     * @generated from field: hookly.v1.ConnectRequest connect = 1;
     */
    value: ConnectRequest;
    case: "connect";
  } | {
    /**
     * @generated from field: hookly.v1.DeliveryAck ack = 2;
     */
    value: DeliveryAck;
    case: "ack";
  } | {
    /**
     * @generated from field: hookly.v1.Heartbeat heartbeat = 3;
     */
    value: Heartbeat;
    case: "heartbeat";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message hookly.v1.StreamRequest.
 * Use `create(StreamRequestSchema)` to create a new message.
 */
export const StreamRequestSchema: GenMessage<StreamRequest> = /*@__PURE__*/
  messageDesc(file_hookly_v1_relay, 0);

/**
 * Messages from edge to home-hub
 *
 * @generated from message hookly.v1.StreamResponse
 */
export type StreamResponse = Message<"hookly.v1.StreamResponse"> & {
  /**
   * @generated from oneof hookly.v1.StreamResponse.message
   */
  message: {
    /**
     * @generated from field: hookly.v1.ConnectResponse connect_response = 1;
     */
    value: ConnectResponse;
    case: "connectResponse";
  } | {
    /**
     * @generated from field: hookly.v1.WebhookEnvelope webhook = 2;
     */
    value: WebhookEnvelope;
    case: "webhook";
  } | {
    /**
     * @generated from field: hookly.v1.Heartbeat heartbeat = 3;
     */
    value: Heartbeat;
    case: "heartbeat";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message hookly.v1.StreamResponse.
 * Use `create(StreamResponseSchema)` to create a new message.
 */
export const StreamResponseSchema: GenMessage<StreamResponse> = /*@__PURE__*/
  messageDesc(file_hookly_v1_relay, 1);

/**
 * Initial connection request with authentication
 *
 * @generated from message hookly.v1.ConnectRequest
 */
export type ConnectRequest = Message<"hookly.v1.ConnectRequest"> & {
  /**
   * @generated from field: string hub_id = 1;
   */
  hubId: string;

  /**
   * Bearer token from CLI login
   *
   * @generated from field: string token = 2;
   */
  token: string;

  /**
   * Endpoints this hub handles
   *
   * @generated from field: repeated string endpoint_ids = 3;
   */
  endpointIds: string[];
};

/**
 * Describes the message hookly.v1.ConnectRequest.
 * Use `create(ConnectRequestSchema)` to create a new message.
 */
export const ConnectRequestSchema: GenMessage<ConnectRequest> = /*@__PURE__*/
  messageDesc(file_hookly_v1_relay, 2);

/**
 * Connection response
 *
 * @generated from message hookly.v1.ConnectResponse
 */
export type ConnectResponse = Message<"hookly.v1.ConnectResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string error = 2;
   */
  error: string;
};

/**
 * Describes the message hookly.v1.ConnectResponse.
 * Use `create(ConnectResponseSchema)` to create a new message.
 */
export const ConnectResponseSchema: GenMessage<ConnectResponse> = /*@__PURE__*/
  messageDesc(file_hookly_v1_relay, 3);

/**
 * Heartbeat for connection health monitoring
 *
 * @generated from message hookly.v1.Heartbeat
 */
export type Heartbeat = Message<"hookly.v1.Heartbeat"> & {
  /**
   * @generated from field: int64 timestamp = 1;
   */
  timestamp: bigint;
};

/**
 * Describes the message hookly.v1.Heartbeat.
 * Use `create(HeartbeatSchema)` to create a new message.
 */
export const HeartbeatSchema: GenMessage<Heartbeat> = /*@__PURE__*/
  messageDesc(file_hookly_v1_relay, 4);

/**
 * Webhook envelope for delivery to home network
 *
 * @generated from message hookly.v1.WebhookEnvelope
 */
export type WebhookEnvelope = Message<"hookly.v1.WebhookEnvelope"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string endpoint_id = 2;
   */
  endpointId: string;

  /**
   * @generated from field: string destination_url = 3;
   */
  destinationUrl: string;

  /**
   * @generated from field: google.protobuf.Timestamp received_at = 4;
   */
  receivedAt?: Timestamp;

  /**
   * @generated from field: map<string, string> headers = 5;
   */
  headers: { [key: string]: string };

  /**
   * @generated from field: bytes payload = 6;
   */
  payload: Uint8Array;

  /**
   * @generated from field: int32 attempt = 7;
   */
  attempt: number;
};

/**
 * Describes the message hookly.v1.WebhookEnvelope.
 * Use `create(WebhookEnvelopeSchema)` to create a new message.
 */
export const WebhookEnvelopeSchema: GenMessage<WebhookEnvelope> = /*@__PURE__*/
  messageDesc(file_hookly_v1_relay, 5);

/**
 * Delivery acknowledgment from home-hub
 *
 * @generated from message hookly.v1.DeliveryAck
 */
export type DeliveryAck = Message<"hookly.v1.DeliveryAck"> & {
  /**
   * @generated from field: string webhook_id = 1;
   */
  webhookId: string;

  /**
   * @generated from field: bool success = 2;
   */
  success: boolean;

  /**
   * @generated from field: int32 status_code = 3;
   */
  statusCode: number;

  /**
   * @generated from field: string error_message = 4;
   */
  errorMessage: string;

  /**
   * true for 4xx, don't retry
   *
   * @generated from field: bool permanent_failure = 5;
   */
  permanentFailure: boolean;
};

/**
 * Describes the message hookly.v1.DeliveryAck.
 * Use `create(DeliveryAckSchema)` to create a new message.
 */
export const DeliveryAckSchema: GenMessage<DeliveryAck> = /*@__PURE__*/
  messageDesc(file_hookly_v1_relay, 6);

/**
 * RelayService handles communication between edge and home-hub.
 * The home-hub initiates a bidirectional stream to receive webhooks and send acks.
 *
 * @generated from service hookly.v1.RelayService
 */
export const RelayService: GenService<{
  /**
   * Stream establishes a bidirectional stream.
   * Home-hub sends auth message, then receives webhooks.
   * Home-hub sends delivery acks to report delivery status.
   *
   * @generated from rpc hookly.v1.RelayService.Stream
   */
  stream: {
    methodKind: "bidi_streaming";
    input: typeof StreamRequestSchema;
    output: typeof StreamResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_hookly_v1_relay, 0);

